// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/fleettemplate"
	"github.com/google/uuid"
)

// FleetTemplateCreate is the builder for creating a FleetTemplate entity.
type FleetTemplateCreate struct {
	config
	mutation *FleetTemplateMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *FleetTemplateCreate) SetKey(v string) *FleetTemplateCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetName sets the "name" field.
func (_c *FleetTemplateCreate) SetName(v string) *FleetTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDefinition sets the "definition" field.
func (_c *FleetTemplateCreate) SetDefinition(v map[string]interface{}) *FleetTemplateCreate {
	_c.mutation.SetDefinition(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *FleetTemplateCreate) SetCreatedBy(v uuid.UUID) *FleetTemplateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *FleetTemplateCreate) SetNillableCreatedBy(v *uuid.UUID) *FleetTemplateCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FleetTemplateCreate) SetCreatedAt(v time.Time) *FleetTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FleetTemplateCreate) SetNillableCreatedAt(v *time.Time) *FleetTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FleetTemplateCreate) SetUpdatedAt(v time.Time) *FleetTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FleetTemplateCreate) SetNillableUpdatedAt(v *time.Time) *FleetTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FleetTemplateCreate) SetID(v uuid.UUID) *FleetTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FleetTemplateCreate) SetNillableID(v *uuid.UUID) *FleetTemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FleetTemplateMutation object of the builder.
func (_c *FleetTemplateCreate) Mutation() *FleetTemplateMutation {
	return _c.mutation
}

// Save creates the FleetTemplate in the database.
func (_c *FleetTemplateCreate) Save(ctx context.Context) (*FleetTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FleetTemplateCreate) SaveX(ctx context.Context) *FleetTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FleetTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FleetTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FleetTemplateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := fleettemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := fleettemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := fleettemplate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FleetTemplateCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`team: missing required field "FleetTemplate.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := fleettemplate.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`team: validator failed for field "FleetTemplate.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`team: missing required field "FleetTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := fleettemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`team: validator failed for field "FleetTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Definition(); !ok {
		return &ValidationError{Name: "definition", err: errors.New(`team: missing required field "FleetTemplate.definition"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`team: missing required field "FleetTemplate.created_at"`)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.UpdatedAt(); !ok {
			return &ValidationError{Name: "updated_at", err: errors.New(`team: missing required field "FleetTemplate.updated_at"`)}
		}
	}
	return nil
}

func (_c *FleetTemplateCreate) sqlSave(ctx context.Context) (*FleetTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FleetTemplateCreate) createSpec() (*FleetTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &FleetTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fleettemplate.Table, sqlgraph.NewFieldSpec(fleettemplate.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(fleettemplate.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(fleettemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Definition(); ok {
		_spec.SetField(fleettemplate.FieldDefinition, field.TypeJSON, value)
		_node.Definition = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(fleettemplate.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(fleettemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(fleettemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FleetTemplateCreateBulk is the builder for creating many FleetTemplate entities in bulk.
type FleetTemplateCreateBulk struct {
	config
	err      error
	builders []*FleetTemplateCreate
}

// Save creates the FleetTemplate entities in the database.
func (_c *FleetTemplateCreateBulk) Save(ctx context.Context) ([]*FleetTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FleetTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FleetTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FleetTemplateCreateBulk) SaveX(ctx context.Context) []*FleetTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FleetTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FleetTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
