// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/fleetmonitorstate"
	"github.com/SAP/astonish/ent/team/predicate"
)

// FleetMonitorStateDelete is the builder for deleting a FleetMonitorState entity.
type FleetMonitorStateDelete struct {
	config
	hooks    []Hook
	mutation *FleetMonitorStateMutation
}

// Where appends a list predicates to the FleetMonitorStateDelete builder.
func (_d *FleetMonitorStateDelete) Where(ps ...predicate.FleetMonitorState) *FleetMonitorStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FleetMonitorStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetMonitorStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FleetMonitorStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fleetmonitorstate.Table, sqlgraph.NewFieldSpec(fleetmonitorstate.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FleetMonitorStateDeleteOne is the builder for deleting a single FleetMonitorState entity.
type FleetMonitorStateDeleteOne struct {
	_d *FleetMonitorStateDelete
}

// Where appends a list predicates to the FleetMonitorStateDelete builder.
func (_d *FleetMonitorStateDeleteOne) Where(ps ...predicate.FleetMonitorState) *FleetMonitorStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FleetMonitorStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fleetmonitorstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetMonitorStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
