// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/schardosin/astonish/ent/team/fleetsetupprofile"
	"github.com/schardosin/astonish/ent/team/predicate"
)

// FleetSetupProfileDelete is the builder for deleting a FleetSetupProfile entity.
type FleetSetupProfileDelete struct {
	config
	hooks    []Hook
	mutation *FleetSetupProfileMutation
}

// Where appends a list predicates to the FleetSetupProfileDelete builder.
func (_d *FleetSetupProfileDelete) Where(ps ...predicate.FleetSetupProfile) *FleetSetupProfileDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FleetSetupProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetSetupProfileDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FleetSetupProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fleetsetupprofile.Table, sqlgraph.NewFieldSpec(fleetsetupprofile.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FleetSetupProfileDeleteOne is the builder for deleting a single FleetSetupProfile entity.
type FleetSetupProfileDeleteOne struct {
	_d *FleetSetupProfileDelete
}

// Where appends a list predicates to the FleetSetupProfileDelete builder.
func (_d *FleetSetupProfileDeleteOne) Where(ps ...predicate.FleetSetupProfile) *FleetSetupProfileDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FleetSetupProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fleetsetupprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FleetSetupProfileDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
