// Code generated by ent, DO NOT EDIT.

package team

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/schardosin/astonish/ent/team/networkpolicy"
)

// NetworkPolicy is the model entity for the NetworkPolicy schema.
type NetworkPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Host pattern: exact, *.example.com, or **.example.com
	Host string `json:"host,omitempty"`
	// Port number; 0 means any port
	Port uint32 `json:"port,omitempty"`
	// Action holds the value of the "action" field.
	Action networkpolicy.Action `json:"action,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NetworkPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case networkpolicy.FieldPort:
			values[i] = new(sql.NullInt64)
		case networkpolicy.FieldHost, networkpolicy.FieldAction:
			values[i] = new(sql.NullString)
		case networkpolicy.FieldCreatedAt, networkpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case networkpolicy.FieldID, networkpolicy.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NetworkPolicy fields.
func (_m *NetworkPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case networkpolicy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case networkpolicy.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case networkpolicy.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = uint32(value.Int64)
			}
		case networkpolicy.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = networkpolicy.Action(value.String)
			}
		case networkpolicy.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case networkpolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case networkpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NetworkPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *NetworkPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this NetworkPolicy.
// Note that you need to call NetworkPolicy.Unwrap() before calling this method if this NetworkPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *NetworkPolicy) Update() *NetworkPolicyUpdateOne {
	return NewNetworkPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the NetworkPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *NetworkPolicy) Unwrap() *NetworkPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("team: NetworkPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *NetworkPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("NetworkPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// NetworkPolicies is a parsable slice of NetworkPolicy.
type NetworkPolicies []*NetworkPolicy
