// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/networkpolicy"
	"github.com/SAP/astonish/ent/team/predicate"
)

// NetworkPolicyDelete is the builder for deleting a NetworkPolicy entity.
type NetworkPolicyDelete struct {
	config
	hooks    []Hook
	mutation *NetworkPolicyMutation
}

// Where appends a list predicates to the NetworkPolicyDelete builder.
func (_d *NetworkPolicyDelete) Where(ps ...predicate.NetworkPolicy) *NetworkPolicyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NetworkPolicyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NetworkPolicyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NetworkPolicyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(networkpolicy.Table, sqlgraph.NewFieldSpec(networkpolicy.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NetworkPolicyDeleteOne is the builder for deleting a single NetworkPolicy entity.
type NetworkPolicyDeleteOne struct {
	_d *NetworkPolicyDelete
}

// Where appends a list predicates to the NetworkPolicyDelete builder.
func (_d *NetworkPolicyDeleteOne) Where(ps ...predicate.NetworkPolicy) *NetworkPolicyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NetworkPolicyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{networkpolicy.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NetworkPolicyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
