// Code generated by ent, DO NOT EDIT.

package team

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/schardosin/astonish/ent/team/sandboxsession"
)

// SandboxSession is the model entity for the SandboxSession schema.
type SandboxSession struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ChatSessionID holds the value of the "chat_session_id" field.
	ChatSessionID string `json:"chat_session_id,omitempty"`
	// Backend holds the value of the "backend" field.
	Backend string `json:"backend,omitempty"`
	// ContainerName holds the value of the "container_name" field.
	ContainerName *string `json:"container_name,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID uuid.UUID `json:"template_id,omitempty"`
	// UpperLayerID holds the value of the "upper_layer_id" field.
	UpperLayerID *string `json:"upper_layer_id,omitempty"`
	// State holds the value of the "state" field.
	State sandboxsession.State `json:"state,omitempty"`
	// PodName holds the value of the "pod_name" field.
	PodName *string `json:"pod_name,omitempty"`
	// NodeName holds the value of the "node_name" field.
	NodeName *string `json:"node_name,omitempty"`
	// ExposedPorts holds the value of the "exposed_ports" field.
	ExposedPorts []interface{} `json:"exposed_ports,omitempty"`
	// BaseDomain holds the value of the "base_domain" field.
	BaseDomain *string `json:"base_domain,omitempty"`
	// Pinned holds the value of the "pinned" field.
	Pinned bool `json:"pinned,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastActiveAt holds the value of the "last_active_at" field.
	LastActiveAt time.Time `json:"last_active_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SandboxSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sandboxsession.FieldCreatedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case sandboxsession.FieldExposedPorts:
			values[i] = new([]byte)
		case sandboxsession.FieldPinned:
			values[i] = new(sql.NullBool)
		case sandboxsession.FieldID, sandboxsession.FieldChatSessionID, sandboxsession.FieldBackend, sandboxsession.FieldContainerName, sandboxsession.FieldUpperLayerID, sandboxsession.FieldState, sandboxsession.FieldPodName, sandboxsession.FieldNodeName, sandboxsession.FieldBaseDomain:
			values[i] = new(sql.NullString)
		case sandboxsession.FieldCreatedAt, sandboxsession.FieldUpdatedAt, sandboxsession.FieldLastActiveAt:
			values[i] = new(sql.NullTime)
		case sandboxsession.FieldTemplateID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SandboxSession fields.
func (_m *SandboxSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sandboxsession.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sandboxsession.FieldChatSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field chat_session_id", values[i])
			} else if value.Valid {
				_m.ChatSessionID = value.String
			}
		case sandboxsession.FieldBackend:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field backend", values[i])
			} else if value.Valid {
				_m.Backend = value.String
			}
		case sandboxsession.FieldContainerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field container_name", values[i])
			} else if value.Valid {
				_m.ContainerName = new(string)
				*_m.ContainerName = value.String
			}
		case sandboxsession.FieldTemplateID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value != nil {
				_m.TemplateID = *value
			}
		case sandboxsession.FieldUpperLayerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upper_layer_id", values[i])
			} else if value.Valid {
				_m.UpperLayerID = new(string)
				*_m.UpperLayerID = value.String
			}
		case sandboxsession.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = sandboxsession.State(value.String)
			}
		case sandboxsession.FieldPodName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pod_name", values[i])
			} else if value.Valid {
				_m.PodName = new(string)
				*_m.PodName = value.String
			}
		case sandboxsession.FieldNodeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_name", values[i])
			} else if value.Valid {
				_m.NodeName = new(string)
				*_m.NodeName = value.String
			}
		case sandboxsession.FieldExposedPorts:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field exposed_ports", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExposedPorts); err != nil {
					return fmt.Errorf("unmarshal field exposed_ports: %w", err)
				}
			}
		case sandboxsession.FieldBaseDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_domain", values[i])
			} else if value.Valid {
				_m.BaseDomain = new(string)
				*_m.BaseDomain = value.String
			}
		case sandboxsession.FieldPinned:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field pinned", values[i])
			} else if value.Valid {
				_m.Pinned = value.Bool
			}
		case sandboxsession.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uuid.UUID)
				*_m.CreatedBy = *value.S.(*uuid.UUID)
			}
		case sandboxsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sandboxsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sandboxsession.FieldLastActiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_active_at", values[i])
			} else if value.Valid {
				_m.LastActiveAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SandboxSession.
// This includes values selected through modifiers, order, etc.
func (_m *SandboxSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SandboxSession.
// Note that you need to call SandboxSession.Unwrap() before calling this method if this SandboxSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SandboxSession) Update() *SandboxSessionUpdateOne {
	return NewSandboxSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SandboxSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SandboxSession) Unwrap() *SandboxSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("team: SandboxSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SandboxSession) String() string {
	var builder strings.Builder
	builder.WriteString("SandboxSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("chat_session_id=")
	builder.WriteString(_m.ChatSessionID)
	builder.WriteString(", ")
	builder.WriteString("backend=")
	builder.WriteString(_m.Backend)
	builder.WriteString(", ")
	if v := _m.ContainerName; v != nil {
		builder.WriteString("container_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("template_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TemplateID))
	builder.WriteString(", ")
	if v := _m.UpperLayerID; v != nil {
		builder.WriteString("upper_layer_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	if v := _m.PodName; v != nil {
		builder.WriteString("pod_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NodeName; v != nil {
		builder.WriteString("node_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("exposed_ports=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExposedPorts))
	builder.WriteString(", ")
	if v := _m.BaseDomain; v != nil {
		builder.WriteString("base_domain=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("pinned=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pinned))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_active_at=")
	builder.WriteString(_m.LastActiveAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SandboxSessions is a parsable slice of SandboxSession.
type SandboxSessions []*SandboxSession
