// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/predicate"
	"github.com/SAP/astonish/ent/team/skill"
	"github.com/SAP/astonish/ent/team/skillfile"
	"github.com/google/uuid"
)

// SkillUpdate is the builder for updating Skill entities.
type SkillUpdate struct {
	config
	hooks    []Hook
	mutation *SkillMutation
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdate) Where(ps ...predicate.Skill) *SkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SkillUpdate) SetName(v string) *SkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableName(v *string) *SkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdate) SetContent(v string) *SkillUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableContent(v *string) *SkillUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetFrontmatter sets the "frontmatter" field.
func (_u *SkillUpdate) SetFrontmatter(v map[string]interface{}) *SkillUpdate {
	_u.mutation.SetFrontmatter(v)
	return _u
}

// ClearFrontmatter clears the value of the "frontmatter" field.
func (_u *SkillUpdate) ClearFrontmatter() *SkillUpdate {
	_u.mutation.ClearFrontmatter()
	return _u
}

// SetValidationStatus sets the "validation_status" field.
func (_u *SkillUpdate) SetValidationStatus(v string) *SkillUpdate {
	_u.mutation.SetValidationStatus(v)
	return _u
}

// SetNillableValidationStatus sets the "validation_status" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableValidationStatus(v *string) *SkillUpdate {
	if v != nil {
		_u.SetValidationStatus(*v)
	}
	return _u
}

// SetValidationMeta sets the "validation_meta" field.
func (_u *SkillUpdate) SetValidationMeta(v map[string]interface{}) *SkillUpdate {
	_u.mutation.SetValidationMeta(v)
	return _u
}

// ClearValidationMeta clears the value of the "validation_meta" field.
func (_u *SkillUpdate) ClearValidationMeta() *SkillUpdate {
	_u.mutation.ClearValidationMeta()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkillUpdate) SetCreatedBy(v uuid.UUID) *SkillUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkillUpdate) SetNillableCreatedBy(v *uuid.UUID) *SkillUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdate) SetUpdatedAt(v time.Time) *SkillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFileIDs adds the "files" edge to the SkillFile entity by IDs.
func (_u *SkillUpdate) AddFileIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the SkillFile entity.
func (_u *SkillUpdate) AddFiles(v ...*SkillFile) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdate) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the SkillFile entity.
func (_u *SkillUpdate) ClearFiles() *SkillUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to SkillFile entities by IDs.
func (_u *SkillUpdate) RemoveFileIDs(ids ...uuid.UUID) *SkillUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to SkillFile entities.
func (_u *SkillUpdate) RemoveFiles(v ...*SkillFile) *SkillUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SkillUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`team: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`team: validator failed for field "Skill.content": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frontmatter(); ok {
		_spec.SetField(skill.FieldFrontmatter, field.TypeJSON, value)
	}
	if _u.mutation.FrontmatterCleared() {
		_spec.ClearField(skill.FieldFrontmatter, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidationStatus(); ok {
		_spec.SetField(skill.FieldValidationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationMeta(); ok {
		_spec.SetField(skill.FieldValidationMeta, field.TypeJSON, value)
	}
	if _u.mutation.ValidationMetaCleared() {
		_spec.ClearField(skill.FieldValidationMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skill.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SkillUpdateOne is the builder for updating a single Skill entity.
type SkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SkillMutation
}

// SetName sets the "name" field.
func (_u *SkillUpdateOne) SetName(v string) *SkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableName(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *SkillUpdateOne) SetContent(v string) *SkillUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableContent(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetFrontmatter sets the "frontmatter" field.
func (_u *SkillUpdateOne) SetFrontmatter(v map[string]interface{}) *SkillUpdateOne {
	_u.mutation.SetFrontmatter(v)
	return _u
}

// ClearFrontmatter clears the value of the "frontmatter" field.
func (_u *SkillUpdateOne) ClearFrontmatter() *SkillUpdateOne {
	_u.mutation.ClearFrontmatter()
	return _u
}

// SetValidationStatus sets the "validation_status" field.
func (_u *SkillUpdateOne) SetValidationStatus(v string) *SkillUpdateOne {
	_u.mutation.SetValidationStatus(v)
	return _u
}

// SetNillableValidationStatus sets the "validation_status" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableValidationStatus(v *string) *SkillUpdateOne {
	if v != nil {
		_u.SetValidationStatus(*v)
	}
	return _u
}

// SetValidationMeta sets the "validation_meta" field.
func (_u *SkillUpdateOne) SetValidationMeta(v map[string]interface{}) *SkillUpdateOne {
	_u.mutation.SetValidationMeta(v)
	return _u
}

// ClearValidationMeta clears the value of the "validation_meta" field.
func (_u *SkillUpdateOne) ClearValidationMeta() *SkillUpdateOne {
	_u.mutation.ClearValidationMeta()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *SkillUpdateOne) SetCreatedBy(v uuid.UUID) *SkillUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *SkillUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *SkillUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SkillUpdateOne) SetUpdatedAt(v time.Time) *SkillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddFileIDs adds the "files" edge to the SkillFile entity by IDs.
func (_u *SkillUpdateOne) AddFileIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the SkillFile entity.
func (_u *SkillUpdateOne) AddFiles(v ...*SkillFile) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the SkillMutation object of the builder.
func (_u *SkillUpdateOne) Mutation() *SkillMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the SkillFile entity.
func (_u *SkillUpdateOne) ClearFiles() *SkillUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to SkillFile entities by IDs.
func (_u *SkillUpdateOne) RemoveFileIDs(ids ...uuid.UUID) *SkillUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to SkillFile entities.
func (_u *SkillUpdateOne) RemoveFiles(v ...*SkillFile) *SkillUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the SkillUpdate builder.
func (_u *SkillUpdateOne) Where(ps ...predicate.Skill) *SkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SkillUpdateOne) Select(field string, fields ...string) *SkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Skill entity.
func (_u *SkillUpdateOne) Save(ctx context.Context) (*Skill, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SkillUpdateOne) SaveX(ctx context.Context) *Skill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SkillUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := skill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SkillUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := skill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`team: validator failed for field "Skill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := skill.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`team: validator failed for field "Skill.content": %w`, err)}
		}
	}
	return nil
}

func (_u *SkillUpdateOne) sqlSave(ctx context.Context) (_node *Skill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(skill.Table, skill.Columns, sqlgraph.NewFieldSpec(skill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`team: missing "Skill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, skill.FieldID)
		for _, f := range fields {
			if !skill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("team: invalid field %q for query", f)}
			}
			if f != skill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(skill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(skill.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Frontmatter(); ok {
		_spec.SetField(skill.FieldFrontmatter, field.TypeJSON, value)
	}
	if _u.mutation.FrontmatterCleared() {
		_spec.ClearField(skill.FieldFrontmatter, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidationStatus(); ok {
		_spec.SetField(skill.FieldValidationStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidationMeta(); ok {
		_spec.SetField(skill.FieldValidationMeta, field.TypeJSON, value)
	}
	if _u.mutation.ValidationMetaCleared() {
		_spec.ClearField(skill.FieldValidationMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(skill.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(skill.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   skill.FilesTable,
			Columns: []string{skill.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(skillfile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Skill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{skill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
