// Code generated by ent, DO NOT EDIT.

package orgnetworkpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/schardosin/astonish/ent/org/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldID, id))
}

// Host applies equality check predicate on the "host" field. It's identical to HostEQ.
func Host(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldHost, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldPort, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// HostEQ applies the EQ predicate on the "host" field.
func HostEQ(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldHost, v))
}

// HostNEQ applies the NEQ predicate on the "host" field.
func HostNEQ(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldHost, v))
}

// HostIn applies the In predicate on the "host" field.
func HostIn(vs ...string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldHost, vs...))
}

// HostNotIn applies the NotIn predicate on the "host" field.
func HostNotIn(vs ...string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldHost, vs...))
}

// HostGT applies the GT predicate on the "host" field.
func HostGT(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldHost, v))
}

// HostGTE applies the GTE predicate on the "host" field.
func HostGTE(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldHost, v))
}

// HostLT applies the LT predicate on the "host" field.
func HostLT(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldHost, v))
}

// HostLTE applies the LTE predicate on the "host" field.
func HostLTE(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldHost, v))
}

// HostContains applies the Contains predicate on the "host" field.
func HostContains(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldContains(FieldHost, v))
}

// HostHasPrefix applies the HasPrefix predicate on the "host" field.
func HostHasPrefix(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldHasPrefix(FieldHost, v))
}

// HostHasSuffix applies the HasSuffix predicate on the "host" field.
func HostHasSuffix(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldHasSuffix(FieldHost, v))
}

// HostEqualFold applies the EqualFold predicate on the "host" field.
func HostEqualFold(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEqualFold(FieldHost, v))
}

// HostContainsFold applies the ContainsFold predicate on the "host" field.
func HostContainsFold(v string) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldContainsFold(FieldHost, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v uint32) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldPort, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v Action) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v Action) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...Action) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...Action) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldAction, vs...))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrgNetworkPolicy) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrgNetworkPolicy) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrgNetworkPolicy) predicate.OrgNetworkPolicy {
	return predicate.OrgNetworkPolicy(sql.NotPredicates(p))
}
