{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astonish.secretName" . }}
  labels:
    {{- include "astonish.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.masterKey }}
  master-key: {{ .Values.secrets.masterKey | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.platformDSN }}
  platform-dsn: {{ .Values.secrets.platformDSN | quote }}
  {{- end }}
{{- end }}
