apiVersion: v1
kind: Secret
metadata:
  name: {{ include "astonish.fullname" . }}-secrets
  labels:
    {{- include "astonish.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.masterKey }}
  master-key: {{ .Values.secrets.masterKey | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.platformDSN }}
  platform-dsn: {{ .Values.secrets.platformDSN | quote }}
  {{- end }}
