// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "slug", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "code", Type: field.TypeString, Default: ""},
		{Name: "version", Type: field.TypeInt, Default: 1},
		{Name: "session_id", Type: field.TypeString, Default: ""},
		{Name: "published_by", Type: field.TypeUUID, Nullable: true},
		{Name: "provider_name", Type: field.TypeString, Nullable: true},
		{Name: "model_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "app_slug",
				Unique:  true,
				Columns: []*schema.Column{AppsColumns[1]},
			},
		},
	}
	// AppStateColumns holds the columns for the "app_state" table.
	AppStateColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeJSON, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// AppStateTable holds the schema information for the "app_state" table.
	AppStateTable = &schema.Table{
		Name:       "app_state",
		Columns:    AppStateColumns,
		PrimaryKey: []*schema.Column{AppStateColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "appstate_app_id_user_id_key",
				Unique:  true,
				Columns: []*schema.Column{AppStateColumns[1], AppStateColumns[2], AppStateColumns[3]},
			},
		},
	}
	// ChatSessionEventsColumns holds the columns for the "chat_session_events" table.
	ChatSessionEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "seq", Type: field.TypeInt64},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "producer_pod", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "chat_session_id", Type: field.TypeString},
	}
	// ChatSessionEventsTable holds the schema information for the "chat_session_events" table.
	ChatSessionEventsTable = &schema.Table{
		Name:       "chat_session_events",
		Columns:    ChatSessionEventsColumns,
		PrimaryKey: []*schema.Column{ChatSessionEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chat_session_events_sessions_chat_events",
				Columns:    []*schema.Column{ChatSessionEventsColumns[6]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "chatsessionevent_chat_session_id_seq",
				Unique:  true,
				Columns: []*schema.Column{ChatSessionEventsColumns[6], ChatSessionEventsColumns[1]},
			},
			{
				Name:    "chatsessionevent_chat_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ChatSessionEventsColumns[6], ChatSessionEventsColumns[5]},
			},
		},
	}
	// CredentialsColumns holds the columns for the "credentials" table.
	CredentialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "cred_type", Type: field.TypeString},
		{Name: "encrypted", Type: field.TypeBytes},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// CredentialsTable holds the schema information for the "credentials" table.
	CredentialsTable = &schema.Table{
		Name:       "credentials",
		Columns:    CredentialsColumns,
		PrimaryKey: []*schema.Column{CredentialsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "credential_name",
				Unique:  true,
				Columns: []*schema.Column{CredentialsColumns[1]},
			},
		},
	}
	// DrillReportsColumns holds the columns for the "drill_reports" table.
	DrillReportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "suite", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "summary", Type: field.TypeString, Default: ""},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "report_data", Type: field.TypeJSON},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// DrillReportsTable holds the schema information for the "drill_reports" table.
	DrillReportsTable = &schema.Table{
		Name:       "drill_reports",
		Columns:    DrillReportsColumns,
		PrimaryKey: []*schema.Column{DrillReportsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "drillreport_suite",
				Unique:  false,
				Columns: []*schema.Column{DrillReportsColumns[1]},
			},
			{
				Name:    "drillreport_created_at",
				Unique:  false,
				Columns: []*schema.Column{DrillReportsColumns[9]},
			},
		},
	}
	// FleetMailboxMessagesColumns holds the columns for the "fleet_mailbox_messages" table.
	FleetMailboxMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString},
		{Name: "recipient", Type: field.TypeString},
		{Name: "sender", Type: field.TypeString},
		{Name: "body", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "mentions", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "delivery_status", Type: field.TypeString, Default: "pending"},
		{Name: "delivered_at", Type: field.TypeTime, Nullable: true},
		{Name: "read_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetMailboxMessagesTable holds the schema information for the "fleet_mailbox_messages" table.
	FleetMailboxMessagesTable = &schema.Table{
		Name:       "fleet_mailbox_messages",
		Columns:    FleetMailboxMessagesColumns,
		PrimaryKey: []*schema.Column{FleetMailboxMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleetmailboxmessage_session_id_recipient_delivery_status",
				Unique:  false,
				Columns: []*schema.Column{FleetMailboxMessagesColumns[1], FleetMailboxMessagesColumns[2], FleetMailboxMessagesColumns[7]},
			},
			{
				Name:    "fleetmailboxmessage_session_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{FleetMailboxMessagesColumns[1], FleetMailboxMessagesColumns[10]},
			},
		},
	}
	// FleetMonitorStateColumns holds the columns for the "fleet_monitor_state" table.
	FleetMonitorStateColumns = []*schema.Column{
		{Name: "plan_key", Type: field.TypeString},
		{Name: "state", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetMonitorStateTable holds the schema information for the "fleet_monitor_state" table.
	FleetMonitorStateTable = &schema.Table{
		Name:       "fleet_monitor_state",
		Columns:    FleetMonitorStateColumns,
		PrimaryKey: []*schema.Column{FleetMonitorStateColumns[0]},
	}
	// FleetPlansColumns holds the columns for the "fleet_plans" table.
	FleetPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "definition", Type: field.TypeJSON},
		{Name: "yaml_content", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: false},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetPlansTable holds the schema information for the "fleet_plans" table.
	FleetPlansTable = &schema.Table{
		Name:       "fleet_plans",
		Columns:    FleetPlansColumns,
		PrimaryKey: []*schema.Column{FleetPlansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleetplan_key",
				Unique:  true,
				Columns: []*schema.Column{FleetPlansColumns[1]},
			},
		},
	}
	// FleetRunStatesColumns holds the columns for the "fleet_run_states" table.
	FleetRunStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString},
		{Name: "plan_key", Type: field.TypeString},
		{Name: "state", Type: field.TypeString},
		{Name: "active_agents", Type: field.TypeJSON},
		{Name: "waiting_agent", Type: field.TypeString, Nullable: true},
		{Name: "ball", Type: field.TypeString, Default: "agents"},
		{Name: "progress", Type: field.TypeJSON},
		{Name: "last_heartbeat_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetRunStatesTable holds the schema information for the "fleet_run_states" table.
	FleetRunStatesTable = &schema.Table{
		Name:       "fleet_run_states",
		Columns:    FleetRunStatesColumns,
		PrimaryKey: []*schema.Column{FleetRunStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleetrunstate_session_id",
				Unique:  true,
				Columns: []*schema.Column{FleetRunStatesColumns[1]},
			},
			{
				Name:    "fleetrunstate_plan_key_state",
				Unique:  false,
				Columns: []*schema.Column{FleetRunStatesColumns[2], FleetRunStatesColumns[3]},
			},
		},
	}
	// FleetSetupDraftsColumns holds the columns for the "fleet_setup_drafts" table.
	FleetSetupDraftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "template_key", Type: field.TypeString},
		{Name: "setup_profile_key", Type: field.TypeString},
		{Name: "collected", Type: field.TypeJSON},
		{Name: "current_step", Type: field.TypeString, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetSetupDraftsTable holds the schema information for the "fleet_setup_drafts" table.
	FleetSetupDraftsTable = &schema.Table{
		Name:       "fleet_setup_drafts",
		Columns:    FleetSetupDraftsColumns,
		PrimaryKey: []*schema.Column{FleetSetupDraftsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleetsetupdraft_created_at",
				Unique:  false,
				Columns: []*schema.Column{FleetSetupDraftsColumns[6]},
			},
		},
	}
	// FleetSetupProfilesColumns holds the columns for the "fleet_setup_profiles" table.
	FleetSetupProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "definition", Type: field.TypeJSON},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetSetupProfilesTable holds the schema information for the "fleet_setup_profiles" table.
	FleetSetupProfilesTable = &schema.Table{
		Name:       "fleet_setup_profiles",
		Columns:    FleetSetupProfilesColumns,
		PrimaryKey: []*schema.Column{FleetSetupProfilesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleetsetupprofile_key",
				Unique:  true,
				Columns: []*schema.Column{FleetSetupProfilesColumns[1]},
			},
		},
	}
	// FleetTasksColumns holds the columns for the "fleet_tasks" table.
	FleetTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "session_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647, Default: ""},
		{Name: "required_capabilities", Type: field.TypeJSON},
		{Name: "claimed_by", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "open"},
		{Name: "result", Type: field.TypeJSON, Nullable: true},
		{Name: "parent_task_id", Type: field.TypeString, Nullable: true},
		{Name: "claimed_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetTasksTable holds the schema information for the "fleet_tasks" table.
	FleetTasksTable = &schema.Table{
		Name:       "fleet_tasks",
		Columns:    FleetTasksColumns,
		PrimaryKey: []*schema.Column{FleetTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleettask_session_id_status",
				Unique:  false,
				Columns: []*schema.Column{FleetTasksColumns[1], FleetTasksColumns[6]},
			},
			{
				Name:    "fleettask_claimed_by",
				Unique:  false,
				Columns: []*schema.Column{FleetTasksColumns[5]},
			},
		},
	}
	// FleetTemplatesColumns holds the columns for the "fleet_templates" table.
	FleetTemplatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "definition", Type: field.TypeJSON},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FleetTemplatesTable holds the schema information for the "fleet_templates" table.
	FleetTemplatesTable = &schema.Table{
		Name:       "fleet_templates",
		Columns:    FleetTemplatesColumns,
		PrimaryKey: []*schema.Column{FleetTemplatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fleettemplate_key",
				Unique:  true,
				Columns: []*schema.Column{FleetTemplatesColumns[1]},
			},
		},
	}
	// FlowsColumns holds the columns for the "flows" table.
	FlowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "definition", Type: field.TypeJSON},
		{Name: "yaml_content", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// FlowsTable holds the schema information for the "flows" table.
	FlowsTable = &schema.Table{
		Name:       "flows",
		Columns:    FlowsColumns,
		PrimaryKey: []*schema.Column{FlowsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "flow_name",
				Unique:  true,
				Columns: []*schema.Column{FlowsColumns[1]},
			},
			{
				Name:    "flow_type",
				Unique:  false,
				Columns: []*schema.Column{FlowsColumns[4]},
			},
		},
	}
	// McpServersColumns holds the columns for the "mcp_servers" table.
	McpServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "command", Type: field.TypeString, Nullable: true},
		{Name: "args", Type: field.TypeJSON, Nullable: true},
		{Name: "env", Type: field.TypeJSON, Nullable: true},
		{Name: "transport", Type: field.TypeString, Default: "stdio"},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "cached_tools", Type: field.TypeJSON, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// McpServersTable holds the schema information for the "mcp_servers" table.
	McpServersTable = &schema.Table{
		Name:       "mcp_servers",
		Columns:    McpServersColumns,
		PrimaryKey: []*schema.Column{McpServersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mcpserver_name",
				Unique:  true,
				Columns: []*schema.Column{McpServersColumns[1]},
			},
		},
	}
	// MemoriesColumns holds the columns for the "memories" table.
	MemoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "chunk_text", Type: field.TypeString},
		{Name: "embedding", Type: field.TypeBytes, Nullable: true, SchemaType: map[string]string{"postgres": "vector(384)"}},
		{Name: "tsv", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "tsvector", "sqlite3": "text"}},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "source_path", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "session_id", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// MemoriesTable holds the schema information for the "memories" table.
	MemoriesTable = &schema.Table{
		Name:       "memories",
		Columns:    MemoriesColumns,
		PrimaryKey: []*schema.Column{MemoriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "memory_session_id",
				Unique:  false,
				Columns: []*schema.Column{MemoriesColumns[8]},
			},
		},
	}
	// NetworkPoliciesColumns holds the columns for the "network_policies" table.
	NetworkPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "host", Type: field.TypeString},
		{Name: "port", Type: field.TypeUint32, Default: 443},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"allow", "deny"}, Default: "allow"},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// NetworkPoliciesTable holds the schema information for the "network_policies" table.
	NetworkPoliciesTable = &schema.Table{
		Name:       "network_policies",
		Columns:    NetworkPoliciesColumns,
		PrimaryKey: []*schema.Column{NetworkPoliciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "networkpolicy_host_port",
				Unique:  true,
				Columns: []*schema.Column{NetworkPoliciesColumns[1], NetworkPoliciesColumns[2]},
			},
		},
	}
	// SandboxSessionsColumns holds the columns for the "sandbox_sessions" table.
	SandboxSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "chat_session_id", Type: field.TypeString},
		{Name: "backend", Type: field.TypeString, Default: "incus"},
		{Name: "container_name", Type: field.TypeString, Nullable: true},
		{Name: "template_id", Type: field.TypeUUID},
		{Name: "upper_layer_id", Type: field.TypeString, Nullable: true},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"creating", "running", "evicting", "evicted", "resuming", "terminated"}, Default: "creating"},
		{Name: "pod_name", Type: field.TypeString, Nullable: true},
		{Name: "node_name", Type: field.TypeString, Nullable: true},
		{Name: "exposed_ports", Type: field.TypeJSON},
		{Name: "base_domain", Type: field.TypeString, Nullable: true},
		{Name: "pinned", Type: field.TypeBool, Default: false},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "last_active_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// SandboxSessionsTable holds the schema information for the "sandbox_sessions" table.
	SandboxSessionsTable = &schema.Table{
		Name:       "sandbox_sessions",
		Columns:    SandboxSessionsColumns,
		PrimaryKey: []*schema.Column{SandboxSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sandboxsession_chat_session_id",
				Unique:  false,
				Columns: []*schema.Column{SandboxSessionsColumns[1]},
			},
			{
				Name:    "sandboxsession_state_last_active_at",
				Unique:  false,
				Columns: []*schema.Column{SandboxSessionsColumns[6], SandboxSessionsColumns[15]},
			},
			{
				Name:    "sandboxsession_upper_layer_id",
				Unique:  false,
				Columns: []*schema.Column{SandboxSessionsColumns[5]},
			},
			{
				Name:    "sandboxsession_container_name",
				Unique:  false,
				Columns: []*schema.Column{SandboxSessionsColumns[3]},
			},
		},
	}
	// ScheduledJobsColumns holds the columns for the "scheduled_jobs" table.
	ScheduledJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "schedule", Type: field.TypeString},
		{Name: "mode", Type: field.TypeEnum, Enums: []string{"routine", "adaptive", "fleet_poll"}, Default: "routine"},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"active", "paused", "completed", "failed"}, Default: "active"},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_status", Type: field.TypeString, Default: "pending"},
		{Name: "last_error", Type: field.TypeString, Default: ""},
		{Name: "consecutive_failures", Type: field.TypeInt, Default: 0},
		{Name: "created_by", Type: field.TypeUUID, Nullable: true},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// ScheduledJobsTable holds the schema information for the "scheduled_jobs" table.
	ScheduledJobsTable = &schema.Table{
		Name:       "scheduled_jobs",
		Columns:    ScheduledJobsColumns,
		PrimaryKey: []*schema.Column{ScheduledJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "scheduledjob_status",
				Unique:  false,
				Columns: []*schema.Column{ScheduledJobsColumns[5]},
			},
			{
				Name:    "scheduledjob_next_run_at",
				Unique:  false,
				Columns: []*schema.Column{ScheduledJobsColumns[7]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "message_count", Type: field.TypeInt, Default: 0},
		{Name: "parent_id", Type: field.TypeString, Nullable: true},
		{Name: "fleet_key", Type: field.TypeString, Default: ""},
		{Name: "fleet_name", Type: field.TypeString, Default: ""},
		{Name: "issue_number", Type: field.TypeInt, Default: 0},
		{Name: "repo", Type: field.TypeString, Default: ""},
		{Name: "workspace_dir", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "provider_name", Type: field.TypeString, Nullable: true},
		{Name: "model_name", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "last_seq", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "session_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[4]},
			},
			{
				Name:    "session_fleet_key",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[5]},
			},
			{
				Name:    "session_updated_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[15]},
			},
		},
	}
	// SessionEventsColumns holds the columns for the "session_events" table.
	SessionEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "event_data", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "session_id", Type: field.TypeString},
	}
	// SessionEventsTable holds the schema information for the "session_events" table.
	SessionEventsTable = &schema.Table{
		Name:       "session_events",
		Columns:    SessionEventsColumns,
		PrimaryKey: []*schema.Column{SessionEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "session_events_sessions_events",
				Columns:    []*schema.Column{SessionEventsColumns[3]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sessionevent_session_id",
				Unique:  false,
				Columns: []*schema.Column{SessionEventsColumns[3]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SkillsColumns holds the columns for the "skills" table.
	SkillsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "frontmatter", Type: field.TypeJSON, Nullable: true},
		{Name: "validation_status", Type: field.TypeString, Default: "unknown"},
		{Name: "validation_meta", Type: field.TypeJSON, Nullable: true},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
	}
	// SkillsTable holds the schema information for the "skills" table.
	SkillsTable = &schema.Table{
		Name:       "skills",
		Columns:    SkillsColumns,
		PrimaryKey: []*schema.Column{SkillsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "skill_name",
				Unique:  true,
				Columns: []*schema.Column{SkillsColumns[1]},
			},
		},
	}
	// SkillFilesColumns holds the columns for the "skill_files" table.
	SkillFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "path", Type: field.TypeString, Default: ""},
		{Name: "filename", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "is_executable", Type: field.TypeBool, Default: false},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "updated_at", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "skill_id", Type: field.TypeUUID},
	}
	// SkillFilesTable holds the schema information for the "skill_files" table.
	SkillFilesTable = &schema.Table{
		Name:       "skill_files",
		Columns:    SkillFilesColumns,
		PrimaryKey: []*schema.Column{SkillFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "skill_files_skills_files",
				Columns:    []*schema.Column{SkillFilesColumns[8]},
				RefColumns: []*schema.Column{SkillsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "skillfile_skill_id",
				Unique:  false,
				Columns: []*schema.Column{SkillFilesColumns[8]},
			},
			{
				Name:    "skillfile_path",
				Unique:  false,
				Columns: []*schema.Column{SkillFilesColumns[1]},
			},
			{
				Name:    "skillfile_skill_id_path_filename",
				Unique:  true,
				Columns: []*schema.Column{SkillFilesColumns[8], SkillFilesColumns[1], SkillFilesColumns[2]},
			},
		},
	}
	// TeamAuditLogColumns holds the columns for the "team_audit_log" table.
	TeamAuditLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "timestamp", Type: field.TypeTime, Default: map[string]schema.Expr{"postgres": "now()", "sqlite3": "(datetime('now'))"}},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "action", Type: field.TypeString},
		{Name: "resource", Type: field.TypeString},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "session_id", Type: field.TypeString, Nullable: true},
	}
	// TeamAuditLogTable holds the schema information for the "team_audit_log" table.
	TeamAuditLogTable = &schema.Table{
		Name:       "team_audit_log",
		Columns:    TeamAuditLogColumns,
		PrimaryKey: []*schema.Column{TeamAuditLogColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "teamauditlog_timestamp",
				Unique:  false,
				Columns: []*schema.Column{TeamAuditLogColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		AppStateTable,
		ChatSessionEventsTable,
		CredentialsTable,
		DrillReportsTable,
		FleetMailboxMessagesTable,
		FleetMonitorStateTable,
		FleetPlansTable,
		FleetRunStatesTable,
		FleetSetupDraftsTable,
		FleetSetupProfilesTable,
		FleetTasksTable,
		FleetTemplatesTable,
		FlowsTable,
		McpServersTable,
		MemoriesTable,
		NetworkPoliciesTable,
		SandboxSessionsTable,
		ScheduledJobsTable,
		SessionsTable,
		SessionEventsTable,
		SettingsTable,
		SkillsTable,
		SkillFilesTable,
		TeamAuditLogTable,
	}
)

func init() {
	AppsTable.Annotation = &entsql.Annotation{
		Table: "apps",
	}
	AppStateTable.Annotation = &entsql.Annotation{
		Table: "app_state",
	}
	ChatSessionEventsTable.ForeignKeys[0].RefTable = SessionsTable
	ChatSessionEventsTable.Annotation = &entsql.Annotation{
		Table: "chat_session_events",
	}
	CredentialsTable.Annotation = &entsql.Annotation{
		Table: "credentials",
	}
	DrillReportsTable.Annotation = &entsql.Annotation{
		Table: "drill_reports",
	}
	FleetMailboxMessagesTable.Annotation = &entsql.Annotation{
		Table: "fleet_mailbox_messages",
	}
	FleetMonitorStateTable.Annotation = &entsql.Annotation{
		Table: "fleet_monitor_state",
	}
	FleetPlansTable.Annotation = &entsql.Annotation{
		Table: "fleet_plans",
	}
	FleetRunStatesTable.Annotation = &entsql.Annotation{
		Table: "fleet_run_states",
	}
	FleetSetupDraftsTable.Annotation = &entsql.Annotation{
		Table: "fleet_setup_drafts",
	}
	FleetSetupProfilesTable.Annotation = &entsql.Annotation{
		Table: "fleet_setup_profiles",
	}
	FleetTasksTable.Annotation = &entsql.Annotation{
		Table: "fleet_tasks",
	}
	FleetTemplatesTable.Annotation = &entsql.Annotation{
		Table: "fleet_templates",
	}
	FlowsTable.Annotation = &entsql.Annotation{
		Table: "flows",
	}
	McpServersTable.Annotation = &entsql.Annotation{
		Table: "mcp_servers",
	}
	MemoriesTable.Annotation = &entsql.Annotation{
		Table: "memories",
	}
	NetworkPoliciesTable.Annotation = &entsql.Annotation{
		Table: "network_policies",
	}
	SandboxSessionsTable.Annotation = &entsql.Annotation{
		Table: "sandbox_sessions",
	}
	ScheduledJobsTable.Annotation = &entsql.Annotation{
		Table: "scheduled_jobs",
	}
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	SessionEventsTable.ForeignKeys[0].RefTable = SessionsTable
	SessionEventsTable.Annotation = &entsql.Annotation{
		Table: "session_events",
	}
	SettingsTable.Annotation = &entsql.Annotation{
		Table: "settings",
	}
	SkillsTable.Annotation = &entsql.Annotation{
		Table: "skills",
	}
	SkillFilesTable.ForeignKeys[0].RefTable = SkillsTable
	SkillFilesTable.Annotation = &entsql.Annotation{
		Table: "skill_files",
	}
	TeamAuditLogTable.Annotation = &entsql.Annotation{
		Table: "team_audit_log",
	}
}
