// Code generated by ent, DO NOT EDIT.

package session

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/schardosin/astonish/ent/team/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTitle, v))
}

// MessageCount applies equality check predicate on the "message_count" field. It's identical to MessageCountEQ.
func MessageCount(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldMessageCount, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentID, v))
}

// FleetKey applies equality check predicate on the "fleet_key" field. It's identical to FleetKeyEQ.
func FleetKey(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFleetKey, v))
}

// FleetName applies equality check predicate on the "fleet_name" field. It's identical to FleetNameEQ.
func FleetName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFleetName, v))
}

// IssueNumber applies equality check predicate on the "issue_number" field. It's identical to IssueNumberEQ.
func IssueNumber(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIssueNumber, v))
}

// Repo applies equality check predicate on the "repo" field. It's identical to RepoEQ.
func Repo(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRepo, v))
}

// WorkspaceDir applies equality check predicate on the "workspace_dir" field. It's identical to WorkspaceDirEQ.
func WorkspaceDir(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkspaceDir, v))
}

// ProviderName applies equality check predicate on the "provider_name" field. It's identical to ProviderNameEQ.
func ProviderName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProviderName, v))
}

// ModelName applies equality check predicate on the "model_name" field. It's identical to ModelNameEQ.
func ModelName(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldModelName, v))
}

// LastSeq applies equality check predicate on the "last_seq" field. It's identical to LastSeqEQ.
func LastSeq(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLastSeq, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldUserID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldTitle, v))
}

// MessageCountEQ applies the EQ predicate on the "message_count" field.
func MessageCountEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldMessageCount, v))
}

// MessageCountNEQ applies the NEQ predicate on the "message_count" field.
func MessageCountNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldMessageCount, v))
}

// MessageCountIn applies the In predicate on the "message_count" field.
func MessageCountIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldMessageCount, vs...))
}

// MessageCountNotIn applies the NotIn predicate on the "message_count" field.
func MessageCountNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldMessageCount, vs...))
}

// MessageCountGT applies the GT predicate on the "message_count" field.
func MessageCountGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldMessageCount, v))
}

// MessageCountGTE applies the GTE predicate on the "message_count" field.
func MessageCountGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldMessageCount, v))
}

// MessageCountLT applies the LT predicate on the "message_count" field.
func MessageCountLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldMessageCount, v))
}

// MessageCountLTE applies the LTE predicate on the "message_count" field.
func MessageCountLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldMessageCount, v))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldParentID, v))
}

// ParentIDContains applies the Contains predicate on the "parent_id" field.
func ParentIDContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldParentID, v))
}

// ParentIDHasPrefix applies the HasPrefix predicate on the "parent_id" field.
func ParentIDHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldParentID, v))
}

// ParentIDHasSuffix applies the HasSuffix predicate on the "parent_id" field.
func ParentIDHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldParentID))
}

// ParentIDEqualFold applies the EqualFold predicate on the "parent_id" field.
func ParentIDEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldParentID, v))
}

// ParentIDContainsFold applies the ContainsFold predicate on the "parent_id" field.
func ParentIDContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldParentID, v))
}

// FleetKeyEQ applies the EQ predicate on the "fleet_key" field.
func FleetKeyEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFleetKey, v))
}

// FleetKeyNEQ applies the NEQ predicate on the "fleet_key" field.
func FleetKeyNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldFleetKey, v))
}

// FleetKeyIn applies the In predicate on the "fleet_key" field.
func FleetKeyIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldFleetKey, vs...))
}

// FleetKeyNotIn applies the NotIn predicate on the "fleet_key" field.
func FleetKeyNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldFleetKey, vs...))
}

// FleetKeyGT applies the GT predicate on the "fleet_key" field.
func FleetKeyGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldFleetKey, v))
}

// FleetKeyGTE applies the GTE predicate on the "fleet_key" field.
func FleetKeyGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldFleetKey, v))
}

// FleetKeyLT applies the LT predicate on the "fleet_key" field.
func FleetKeyLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldFleetKey, v))
}

// FleetKeyLTE applies the LTE predicate on the "fleet_key" field.
func FleetKeyLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldFleetKey, v))
}

// FleetKeyContains applies the Contains predicate on the "fleet_key" field.
func FleetKeyContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldFleetKey, v))
}

// FleetKeyHasPrefix applies the HasPrefix predicate on the "fleet_key" field.
func FleetKeyHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldFleetKey, v))
}

// FleetKeyHasSuffix applies the HasSuffix predicate on the "fleet_key" field.
func FleetKeyHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldFleetKey, v))
}

// FleetKeyEqualFold applies the EqualFold predicate on the "fleet_key" field.
func FleetKeyEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldFleetKey, v))
}

// FleetKeyContainsFold applies the ContainsFold predicate on the "fleet_key" field.
func FleetKeyContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldFleetKey, v))
}

// FleetNameEQ applies the EQ predicate on the "fleet_name" field.
func FleetNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldFleetName, v))
}

// FleetNameNEQ applies the NEQ predicate on the "fleet_name" field.
func FleetNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldFleetName, v))
}

// FleetNameIn applies the In predicate on the "fleet_name" field.
func FleetNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldFleetName, vs...))
}

// FleetNameNotIn applies the NotIn predicate on the "fleet_name" field.
func FleetNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldFleetName, vs...))
}

// FleetNameGT applies the GT predicate on the "fleet_name" field.
func FleetNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldFleetName, v))
}

// FleetNameGTE applies the GTE predicate on the "fleet_name" field.
func FleetNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldFleetName, v))
}

// FleetNameLT applies the LT predicate on the "fleet_name" field.
func FleetNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldFleetName, v))
}

// FleetNameLTE applies the LTE predicate on the "fleet_name" field.
func FleetNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldFleetName, v))
}

// FleetNameContains applies the Contains predicate on the "fleet_name" field.
func FleetNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldFleetName, v))
}

// FleetNameHasPrefix applies the HasPrefix predicate on the "fleet_name" field.
func FleetNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldFleetName, v))
}

// FleetNameHasSuffix applies the HasSuffix predicate on the "fleet_name" field.
func FleetNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldFleetName, v))
}

// FleetNameEqualFold applies the EqualFold predicate on the "fleet_name" field.
func FleetNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldFleetName, v))
}

// FleetNameContainsFold applies the ContainsFold predicate on the "fleet_name" field.
func FleetNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldFleetName, v))
}

// IssueNumberEQ applies the EQ predicate on the "issue_number" field.
func IssueNumberEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldIssueNumber, v))
}

// IssueNumberNEQ applies the NEQ predicate on the "issue_number" field.
func IssueNumberNEQ(v int) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldIssueNumber, v))
}

// IssueNumberIn applies the In predicate on the "issue_number" field.
func IssueNumberIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldIssueNumber, vs...))
}

// IssueNumberNotIn applies the NotIn predicate on the "issue_number" field.
func IssueNumberNotIn(vs ...int) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldIssueNumber, vs...))
}

// IssueNumberGT applies the GT predicate on the "issue_number" field.
func IssueNumberGT(v int) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldIssueNumber, v))
}

// IssueNumberGTE applies the GTE predicate on the "issue_number" field.
func IssueNumberGTE(v int) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldIssueNumber, v))
}

// IssueNumberLT applies the LT predicate on the "issue_number" field.
func IssueNumberLT(v int) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldIssueNumber, v))
}

// IssueNumberLTE applies the LTE predicate on the "issue_number" field.
func IssueNumberLTE(v int) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldIssueNumber, v))
}

// RepoEQ applies the EQ predicate on the "repo" field.
func RepoEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldRepo, v))
}

// RepoNEQ applies the NEQ predicate on the "repo" field.
func RepoNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldRepo, v))
}

// RepoIn applies the In predicate on the "repo" field.
func RepoIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldRepo, vs...))
}

// RepoNotIn applies the NotIn predicate on the "repo" field.
func RepoNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldRepo, vs...))
}

// RepoGT applies the GT predicate on the "repo" field.
func RepoGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldRepo, v))
}

// RepoGTE applies the GTE predicate on the "repo" field.
func RepoGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldRepo, v))
}

// RepoLT applies the LT predicate on the "repo" field.
func RepoLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldRepo, v))
}

// RepoLTE applies the LTE predicate on the "repo" field.
func RepoLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldRepo, v))
}

// RepoContains applies the Contains predicate on the "repo" field.
func RepoContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldRepo, v))
}

// RepoHasPrefix applies the HasPrefix predicate on the "repo" field.
func RepoHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldRepo, v))
}

// RepoHasSuffix applies the HasSuffix predicate on the "repo" field.
func RepoHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldRepo, v))
}

// RepoEqualFold applies the EqualFold predicate on the "repo" field.
func RepoEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldRepo, v))
}

// RepoContainsFold applies the ContainsFold predicate on the "repo" field.
func RepoContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldRepo, v))
}

// WorkspaceDirEQ applies the EQ predicate on the "workspace_dir" field.
func WorkspaceDirEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldWorkspaceDir, v))
}

// WorkspaceDirNEQ applies the NEQ predicate on the "workspace_dir" field.
func WorkspaceDirNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldWorkspaceDir, v))
}

// WorkspaceDirIn applies the In predicate on the "workspace_dir" field.
func WorkspaceDirIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldWorkspaceDir, vs...))
}

// WorkspaceDirNotIn applies the NotIn predicate on the "workspace_dir" field.
func WorkspaceDirNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldWorkspaceDir, vs...))
}

// WorkspaceDirGT applies the GT predicate on the "workspace_dir" field.
func WorkspaceDirGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldWorkspaceDir, v))
}

// WorkspaceDirGTE applies the GTE predicate on the "workspace_dir" field.
func WorkspaceDirGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldWorkspaceDir, v))
}

// WorkspaceDirLT applies the LT predicate on the "workspace_dir" field.
func WorkspaceDirLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldWorkspaceDir, v))
}

// WorkspaceDirLTE applies the LTE predicate on the "workspace_dir" field.
func WorkspaceDirLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldWorkspaceDir, v))
}

// WorkspaceDirContains applies the Contains predicate on the "workspace_dir" field.
func WorkspaceDirContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldWorkspaceDir, v))
}

// WorkspaceDirHasPrefix applies the HasPrefix predicate on the "workspace_dir" field.
func WorkspaceDirHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldWorkspaceDir, v))
}

// WorkspaceDirHasSuffix applies the HasSuffix predicate on the "workspace_dir" field.
func WorkspaceDirHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldWorkspaceDir, v))
}

// WorkspaceDirIsNil applies the IsNil predicate on the "workspace_dir" field.
func WorkspaceDirIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldWorkspaceDir))
}

// WorkspaceDirNotNil applies the NotNil predicate on the "workspace_dir" field.
func WorkspaceDirNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldWorkspaceDir))
}

// WorkspaceDirEqualFold applies the EqualFold predicate on the "workspace_dir" field.
func WorkspaceDirEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldWorkspaceDir, v))
}

// WorkspaceDirContainsFold applies the ContainsFold predicate on the "workspace_dir" field.
func WorkspaceDirContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldWorkspaceDir, v))
}

// ProviderNameEQ applies the EQ predicate on the "provider_name" field.
func ProviderNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldProviderName, v))
}

// ProviderNameNEQ applies the NEQ predicate on the "provider_name" field.
func ProviderNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldProviderName, v))
}

// ProviderNameIn applies the In predicate on the "provider_name" field.
func ProviderNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldProviderName, vs...))
}

// ProviderNameNotIn applies the NotIn predicate on the "provider_name" field.
func ProviderNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldProviderName, vs...))
}

// ProviderNameGT applies the GT predicate on the "provider_name" field.
func ProviderNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldProviderName, v))
}

// ProviderNameGTE applies the GTE predicate on the "provider_name" field.
func ProviderNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldProviderName, v))
}

// ProviderNameLT applies the LT predicate on the "provider_name" field.
func ProviderNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldProviderName, v))
}

// ProviderNameLTE applies the LTE predicate on the "provider_name" field.
func ProviderNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldProviderName, v))
}

// ProviderNameContains applies the Contains predicate on the "provider_name" field.
func ProviderNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldProviderName, v))
}

// ProviderNameHasPrefix applies the HasPrefix predicate on the "provider_name" field.
func ProviderNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldProviderName, v))
}

// ProviderNameHasSuffix applies the HasSuffix predicate on the "provider_name" field.
func ProviderNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldProviderName, v))
}

// ProviderNameIsNil applies the IsNil predicate on the "provider_name" field.
func ProviderNameIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldProviderName))
}

// ProviderNameNotNil applies the NotNil predicate on the "provider_name" field.
func ProviderNameNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldProviderName))
}

// ProviderNameEqualFold applies the EqualFold predicate on the "provider_name" field.
func ProviderNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldProviderName, v))
}

// ProviderNameContainsFold applies the ContainsFold predicate on the "provider_name" field.
func ProviderNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldProviderName, v))
}

// ModelNameEQ applies the EQ predicate on the "model_name" field.
func ModelNameEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldModelName, v))
}

// ModelNameNEQ applies the NEQ predicate on the "model_name" field.
func ModelNameNEQ(v string) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldModelName, v))
}

// ModelNameIn applies the In predicate on the "model_name" field.
func ModelNameIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldModelName, vs...))
}

// ModelNameNotIn applies the NotIn predicate on the "model_name" field.
func ModelNameNotIn(vs ...string) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldModelName, vs...))
}

// ModelNameGT applies the GT predicate on the "model_name" field.
func ModelNameGT(v string) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldModelName, v))
}

// ModelNameGTE applies the GTE predicate on the "model_name" field.
func ModelNameGTE(v string) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldModelName, v))
}

// ModelNameLT applies the LT predicate on the "model_name" field.
func ModelNameLT(v string) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldModelName, v))
}

// ModelNameLTE applies the LTE predicate on the "model_name" field.
func ModelNameLTE(v string) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldModelName, v))
}

// ModelNameContains applies the Contains predicate on the "model_name" field.
func ModelNameContains(v string) predicate.Session {
	return predicate.Session(sql.FieldContains(FieldModelName, v))
}

// ModelNameHasPrefix applies the HasPrefix predicate on the "model_name" field.
func ModelNameHasPrefix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasPrefix(FieldModelName, v))
}

// ModelNameHasSuffix applies the HasSuffix predicate on the "model_name" field.
func ModelNameHasSuffix(v string) predicate.Session {
	return predicate.Session(sql.FieldHasSuffix(FieldModelName, v))
}

// ModelNameIsNil applies the IsNil predicate on the "model_name" field.
func ModelNameIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldModelName))
}

// ModelNameNotNil applies the NotNil predicate on the "model_name" field.
func ModelNameNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldModelName))
}

// ModelNameEqualFold applies the EqualFold predicate on the "model_name" field.
func ModelNameEqualFold(v string) predicate.Session {
	return predicate.Session(sql.FieldEqualFold(FieldModelName, v))
}

// ModelNameContainsFold applies the ContainsFold predicate on the "model_name" field.
func ModelNameContainsFold(v string) predicate.Session {
	return predicate.Session(sql.FieldContainsFold(FieldModelName, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.Session {
	return predicate.Session(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.Session {
	return predicate.Session(sql.FieldNotNull(FieldMetadata))
}

// LastSeqEQ applies the EQ predicate on the "last_seq" field.
func LastSeqEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldLastSeq, v))
}

// LastSeqNEQ applies the NEQ predicate on the "last_seq" field.
func LastSeqNEQ(v int64) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldLastSeq, v))
}

// LastSeqIn applies the In predicate on the "last_seq" field.
func LastSeqIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldLastSeq, vs...))
}

// LastSeqNotIn applies the NotIn predicate on the "last_seq" field.
func LastSeqNotIn(vs ...int64) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldLastSeq, vs...))
}

// LastSeqGT applies the GT predicate on the "last_seq" field.
func LastSeqGT(v int64) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldLastSeq, v))
}

// LastSeqGTE applies the GTE predicate on the "last_seq" field.
func LastSeqGTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldLastSeq, v))
}

// LastSeqLT applies the LT predicate on the "last_seq" field.
func LastSeqLT(v int64) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldLastSeq, v))
}

// LastSeqLTE applies the LTE predicate on the "last_seq" field.
func LastSeqLTE(v int64) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldLastSeq, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Session {
	return predicate.Session(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Session {
	return predicate.Session(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.SessionEvent) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChatEvents applies the HasEdge predicate on the "chat_events" edge.
func HasChatEvents() predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChatEventsTable, ChatEventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatEventsWith applies the HasEdge predicate on the "chat_events" edge with a given conditions (other predicates).
func HasChatEventsWith(preds ...predicate.ChatSessionEvent) predicate.Session {
	return predicate.Session(func(s *sql.Selector) {
		step := newChatEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Session) predicate.Session {
	return predicate.Session(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Session) predicate.Session {
	return predicate.Session(sql.NotPredicates(p))
}
