// Code generated by ent, DO NOT EDIT.

package org

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/schardosin/astonish/ent/org/orgapp"
)

// OrgApp is the model entity for the OrgApp schema.
type OrgApp struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Definition holds the value of the "definition" field.
	Definition map[string]interface{} `json:"definition,omitempty"`
	// PromotedBy holds the value of the "promoted_by" field.
	PromotedBy uuid.UUID `json:"promoted_by,omitempty"`
	// PromotedFromTeam holds the value of the "promoted_from_team" field.
	PromotedFromTeam *string `json:"promoted_from_team,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrgApp) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orgapp.FieldDefinition:
			values[i] = new([]byte)
		case orgapp.FieldSlug, orgapp.FieldName, orgapp.FieldDescription, orgapp.FieldPromotedFromTeam:
			values[i] = new(sql.NullString)
		case orgapp.FieldCreatedAt, orgapp.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case orgapp.FieldID, orgapp.FieldPromotedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrgApp fields.
func (_m *OrgApp) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orgapp.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case orgapp.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case orgapp.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case orgapp.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case orgapp.FieldDefinition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field definition", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Definition); err != nil {
					return fmt.Errorf("unmarshal field definition: %w", err)
				}
			}
		case orgapp.FieldPromotedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field promoted_by", values[i])
			} else if value != nil {
				_m.PromotedBy = *value
			}
		case orgapp.FieldPromotedFromTeam:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field promoted_from_team", values[i])
			} else if value.Valid {
				_m.PromotedFromTeam = new(string)
				*_m.PromotedFromTeam = value.String
			}
		case orgapp.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case orgapp.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrgApp.
// This includes values selected through modifiers, order, etc.
func (_m *OrgApp) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OrgApp.
// Note that you need to call OrgApp.Unwrap() before calling this method if this OrgApp
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrgApp) Update() *OrgAppUpdateOne {
	return NewOrgAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrgApp entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrgApp) Unwrap() *OrgApp {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("org: OrgApp is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrgApp) String() string {
	var builder strings.Builder
	builder.WriteString("OrgApp(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("definition=")
	builder.WriteString(fmt.Sprintf("%v", _m.Definition))
	builder.WriteString(", ")
	builder.WriteString("promoted_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromotedBy))
	builder.WriteString(", ")
	if v := _m.PromotedFromTeam; v != nil {
		builder.WriteString("promoted_from_team=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrgApps is a parsable slice of OrgApp.
type OrgApps []*OrgApp
