// Code generated by ent, DO NOT EDIT.

package org

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/org/orgencryptionkey"
	"github.com/SAP/astonish/ent/org/predicate"
)

// OrgEncryptionKeyDelete is the builder for deleting a OrgEncryptionKey entity.
type OrgEncryptionKeyDelete struct {
	config
	hooks    []Hook
	mutation *OrgEncryptionKeyMutation
}

// Where appends a list predicates to the OrgEncryptionKeyDelete builder.
func (_d *OrgEncryptionKeyDelete) Where(ps ...predicate.OrgEncryptionKey) *OrgEncryptionKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrgEncryptionKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgEncryptionKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrgEncryptionKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orgencryptionkey.Table, sqlgraph.NewFieldSpec(orgencryptionkey.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrgEncryptionKeyDeleteOne is the builder for deleting a single OrgEncryptionKey entity.
type OrgEncryptionKeyDeleteOne struct {
	_d *OrgEncryptionKeyDelete
}

// Where appends a list predicates to the OrgEncryptionKeyDelete builder.
func (_d *OrgEncryptionKeyDeleteOne) Where(ps ...predicate.OrgEncryptionKey) *OrgEncryptionKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrgEncryptionKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orgencryptionkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgEncryptionKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
