// Code generated by ent, DO NOT EDIT.

package org

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/schardosin/astonish/ent/org/orgmemory"
	"github.com/schardosin/astonish/ent/org/predicate"
)

// OrgMemoryDelete is the builder for deleting a OrgMemory entity.
type OrgMemoryDelete struct {
	config
	hooks    []Hook
	mutation *OrgMemoryMutation
}

// Where appends a list predicates to the OrgMemoryDelete builder.
func (_d *OrgMemoryDelete) Where(ps ...predicate.OrgMemory) *OrgMemoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrgMemoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgMemoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrgMemoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orgmemory.Table, sqlgraph.NewFieldSpec(orgmemory.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrgMemoryDeleteOne is the builder for deleting a single OrgMemory entity.
type OrgMemoryDeleteOne struct {
	_d *OrgMemoryDelete
}

// Where appends a list predicates to the OrgMemoryDelete builder.
func (_d *OrgMemoryDeleteOne) Where(ps ...predicate.OrgMemory) *OrgMemoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrgMemoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orgmemory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgMemoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
