// Code generated by ent, DO NOT EDIT.

package org

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/org/team"
	"github.com/SAP/astonish/ent/org/teammembership"
	"github.com/google/uuid"
)

// TeamMembershipCreate is the builder for creating a TeamMembership entity.
type TeamMembershipCreate struct {
	config
	mutation *TeamMembershipMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *TeamMembershipCreate) SetUserID(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *TeamMembershipCreate) SetTeamID(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *TeamMembershipCreate) SetRole(v teammembership.Role) *TeamMembershipCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableRole(v *teammembership.Role) *TeamMembershipCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *TeamMembershipCreate) SetJoinedAt(v time.Time) *TeamMembershipCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableJoinedAt(v *time.Time) *TeamMembershipCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamMembershipCreate) SetID(v uuid.UUID) *TeamMembershipCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TeamMembershipCreate) SetNillableID(v *uuid.UUID) *TeamMembershipCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *TeamMembershipCreate) SetTeam(v *Team) *TeamMembershipCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the TeamMembershipMutation object of the builder.
func (_c *TeamMembershipCreate) Mutation() *TeamMembershipMutation {
	return _c.mutation
}

// Save creates the TeamMembership in the database.
func (_c *TeamMembershipCreate) Save(ctx context.Context) (*TeamMembership, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamMembershipCreate) SaveX(ctx context.Context) *TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamMembershipCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := teammembership.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := teammembership.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := teammembership.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamMembershipCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`org: missing required field "TeamMembership.user_id"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`org: missing required field "TeamMembership.team_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`org: missing required field "TeamMembership.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := teammembership.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`org: validator failed for field "TeamMembership.role": %w`, err)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.JoinedAt(); !ok {
			return &ValidationError{Name: "joined_at", err: errors.New(`org: missing required field "TeamMembership.joined_at"`)}
		}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`org: missing required edge "TeamMembership.team"`)}
	}
	return nil
}

func (_c *TeamMembershipCreate) sqlSave(ctx context.Context) (*TeamMembership, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamMembershipCreate) createSpec() (*TeamMembership, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamMembership{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(teammembership.Table, sqlgraph.NewFieldSpec(teammembership.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(teammembership.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(teammembership.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(teammembership.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   teammembership.TeamTable,
			Columns: []string{teammembership.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamMembershipCreateBulk is the builder for creating many TeamMembership entities in bulk.
type TeamMembershipCreateBulk struct {
	config
	err      error
	builders []*TeamMembershipCreate
}

// Save creates the TeamMembership entities in the database.
func (_c *TeamMembershipCreateBulk) Save(ctx context.Context) ([]*TeamMembership, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TeamMembership, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMembershipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) SaveX(ctx context.Context) []*TeamMembership {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamMembershipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamMembershipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
