// Code generated by ent, DO NOT EDIT.

package personal

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/SAP/astonish/ent/personal/migrate"
	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SAP/astonish/ent/personal/app"
	"github.com/SAP/astonish/ent/personal/appstate"
	"github.com/SAP/astonish/ent/personal/credential"
	"github.com/SAP/astonish/ent/personal/flow"
	"github.com/SAP/astonish/ent/personal/memory"
	"github.com/SAP/astonish/ent/personal/personalsettings"
	"github.com/SAP/astonish/ent/personal/scheduledjob"
	"github.com/SAP/astonish/ent/personal/session"
	"github.com/SAP/astonish/ent/personal/sessionevent"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// App is the client for interacting with the App builders.
	App *AppClient
	// AppState is the client for interacting with the AppState builders.
	AppState *AppStateClient
	// Credential is the client for interacting with the Credential builders.
	Credential *CredentialClient
	// Flow is the client for interacting with the Flow builders.
	Flow *FlowClient
	// Memory is the client for interacting with the Memory builders.
	Memory *MemoryClient
	// PersonalSettings is the client for interacting with the PersonalSettings builders.
	PersonalSettings *PersonalSettingsClient
	// ScheduledJob is the client for interacting with the ScheduledJob builders.
	ScheduledJob *ScheduledJobClient
	// Session is the client for interacting with the Session builders.
	Session *SessionClient
	// SessionEvent is the client for interacting with the SessionEvent builders.
	SessionEvent *SessionEventClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.App = NewAppClient(c.config)
	c.AppState = NewAppStateClient(c.config)
	c.Credential = NewCredentialClient(c.config)
	c.Flow = NewFlowClient(c.config)
	c.Memory = NewMemoryClient(c.config)
	c.PersonalSettings = NewPersonalSettingsClient(c.config)
	c.ScheduledJob = NewScheduledJobClient(c.config)
	c.Session = NewSessionClient(c.config)
	c.SessionEvent = NewSessionEventClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("personal: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("personal: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		App:              NewAppClient(cfg),
		AppState:         NewAppStateClient(cfg),
		Credential:       NewCredentialClient(cfg),
		Flow:             NewFlowClient(cfg),
		Memory:           NewMemoryClient(cfg),
		PersonalSettings: NewPersonalSettingsClient(cfg),
		ScheduledJob:     NewScheduledJobClient(cfg),
		Session:          NewSessionClient(cfg),
		SessionEvent:     NewSessionEventClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		App:              NewAppClient(cfg),
		AppState:         NewAppStateClient(cfg),
		Credential:       NewCredentialClient(cfg),
		Flow:             NewFlowClient(cfg),
		Memory:           NewMemoryClient(cfg),
		PersonalSettings: NewPersonalSettingsClient(cfg),
		ScheduledJob:     NewScheduledJobClient(cfg),
		Session:          NewSessionClient(cfg),
		SessionEvent:     NewSessionEventClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		App.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.App, c.AppState, c.Credential, c.Flow, c.Memory, c.PersonalSettings,
		c.ScheduledJob, c.Session, c.SessionEvent,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.App, c.AppState, c.Credential, c.Flow, c.Memory, c.PersonalSettings,
		c.ScheduledJob, c.Session, c.SessionEvent,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AppMutation:
		return c.App.mutate(ctx, m)
	case *AppStateMutation:
		return c.AppState.mutate(ctx, m)
	case *CredentialMutation:
		return c.Credential.mutate(ctx, m)
	case *FlowMutation:
		return c.Flow.mutate(ctx, m)
	case *MemoryMutation:
		return c.Memory.mutate(ctx, m)
	case *PersonalSettingsMutation:
		return c.PersonalSettings.mutate(ctx, m)
	case *ScheduledJobMutation:
		return c.ScheduledJob.mutate(ctx, m)
	case *SessionMutation:
		return c.Session.mutate(ctx, m)
	case *SessionEventMutation:
		return c.SessionEvent.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("personal: unknown mutation type %T", m)
	}
}

// AppClient is a client for the App schema.
type AppClient struct {
	config
}

// NewAppClient returns a client for the App from the given config.
func NewAppClient(c config) *AppClient {
	return &AppClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `app.Hooks(f(g(h())))`.
func (c *AppClient) Use(hooks ...Hook) {
	c.hooks.App = append(c.hooks.App, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `app.Intercept(f(g(h())))`.
func (c *AppClient) Intercept(interceptors ...Interceptor) {
	c.inters.App = append(c.inters.App, interceptors...)
}

// Create returns a builder for creating a App entity.
func (c *AppClient) Create() *AppCreate {
	mutation := newAppMutation(c.config, OpCreate)
	return &AppCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of App entities.
func (c *AppClient) CreateBulk(builders ...*AppCreate) *AppCreateBulk {
	return &AppCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppClient) MapCreateBulk(slice any, setFunc func(*AppCreate, int)) *AppCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppCreateBulk{err: fmt.Errorf("calling to AppClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for App.
func (c *AppClient) Update() *AppUpdate {
	mutation := newAppMutation(c.config, OpUpdate)
	return &AppUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppClient) UpdateOne(_m *App) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withApp(_m))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppClient) UpdateOneID(id uuid.UUID) *AppUpdateOne {
	mutation := newAppMutation(c.config, OpUpdateOne, withAppID(id))
	return &AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for App.
func (c *AppClient) Delete() *AppDelete {
	mutation := newAppMutation(c.config, OpDelete)
	return &AppDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppClient) DeleteOne(_m *App) *AppDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppClient) DeleteOneID(id uuid.UUID) *AppDeleteOne {
	builder := c.Delete().Where(app.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppDeleteOne{builder}
}

// Query returns a query builder for App.
func (c *AppClient) Query() *AppQuery {
	return &AppQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApp},
		inters: c.Interceptors(),
	}
}

// Get returns a App entity by its id.
func (c *AppClient) Get(ctx context.Context, id uuid.UUID) (*App, error) {
	return c.Query().Where(app.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppClient) GetX(ctx context.Context, id uuid.UUID) *App {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryState queries the state edge of a App.
func (c *AppClient) QueryState(_m *App) *AppStateQuery {
	query := (&AppStateClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, id),
			sqlgraph.To(appstate.Table, appstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.StateTable, app.StateColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AppClient) Hooks() []Hook {
	return c.hooks.App
}

// Interceptors returns the client interceptors.
func (c *AppClient) Interceptors() []Interceptor {
	return c.inters.App
}

func (c *AppClient) mutate(ctx context.Context, m *AppMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown App mutation op: %q", m.Op())
	}
}

// AppStateClient is a client for the AppState schema.
type AppStateClient struct {
	config
}

// NewAppStateClient returns a client for the AppState from the given config.
func NewAppStateClient(c config) *AppStateClient {
	return &AppStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `appstate.Hooks(f(g(h())))`.
func (c *AppStateClient) Use(hooks ...Hook) {
	c.hooks.AppState = append(c.hooks.AppState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `appstate.Intercept(f(g(h())))`.
func (c *AppStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.AppState = append(c.inters.AppState, interceptors...)
}

// Create returns a builder for creating a AppState entity.
func (c *AppStateClient) Create() *AppStateCreate {
	mutation := newAppStateMutation(c.config, OpCreate)
	return &AppStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AppState entities.
func (c *AppStateClient) CreateBulk(builders ...*AppStateCreate) *AppStateCreateBulk {
	return &AppStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AppStateClient) MapCreateBulk(slice any, setFunc func(*AppStateCreate, int)) *AppStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AppStateCreateBulk{err: fmt.Errorf("calling to AppStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AppStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AppStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AppState.
func (c *AppStateClient) Update() *AppStateUpdate {
	mutation := newAppStateMutation(c.config, OpUpdate)
	return &AppStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AppStateClient) UpdateOne(_m *AppState) *AppStateUpdateOne {
	mutation := newAppStateMutation(c.config, OpUpdateOne, withAppState(_m))
	return &AppStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AppStateClient) UpdateOneID(id uuid.UUID) *AppStateUpdateOne {
	mutation := newAppStateMutation(c.config, OpUpdateOne, withAppStateID(id))
	return &AppStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AppState.
func (c *AppStateClient) Delete() *AppStateDelete {
	mutation := newAppStateMutation(c.config, OpDelete)
	return &AppStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AppStateClient) DeleteOne(_m *AppState) *AppStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AppStateClient) DeleteOneID(id uuid.UUID) *AppStateDeleteOne {
	builder := c.Delete().Where(appstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AppStateDeleteOne{builder}
}

// Query returns a query builder for AppState.
func (c *AppStateClient) Query() *AppStateQuery {
	return &AppStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAppState},
		inters: c.Interceptors(),
	}
}

// Get returns a AppState entity by its id.
func (c *AppStateClient) Get(ctx context.Context, id uuid.UUID) (*AppState, error) {
	return c.Query().Where(appstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AppStateClient) GetX(ctx context.Context, id uuid.UUID) *AppState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryApp queries the app edge of a AppState.
func (c *AppStateClient) QueryApp(_m *AppState) *AppQuery {
	query := (&AppClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(appstate.Table, appstate.FieldID, id),
			sqlgraph.To(app.Table, app.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, appstate.AppTable, appstate.AppColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *AppStateClient) Hooks() []Hook {
	return c.hooks.AppState
}

// Interceptors returns the client interceptors.
func (c *AppStateClient) Interceptors() []Interceptor {
	return c.inters.AppState
}

func (c *AppStateClient) mutate(ctx context.Context, m *AppStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AppStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AppStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AppStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AppStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown AppState mutation op: %q", m.Op())
	}
}

// CredentialClient is a client for the Credential schema.
type CredentialClient struct {
	config
}

// NewCredentialClient returns a client for the Credential from the given config.
func NewCredentialClient(c config) *CredentialClient {
	return &CredentialClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `credential.Hooks(f(g(h())))`.
func (c *CredentialClient) Use(hooks ...Hook) {
	c.hooks.Credential = append(c.hooks.Credential, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `credential.Intercept(f(g(h())))`.
func (c *CredentialClient) Intercept(interceptors ...Interceptor) {
	c.inters.Credential = append(c.inters.Credential, interceptors...)
}

// Create returns a builder for creating a Credential entity.
func (c *CredentialClient) Create() *CredentialCreate {
	mutation := newCredentialMutation(c.config, OpCreate)
	return &CredentialCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Credential entities.
func (c *CredentialClient) CreateBulk(builders ...*CredentialCreate) *CredentialCreateBulk {
	return &CredentialCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CredentialClient) MapCreateBulk(slice any, setFunc func(*CredentialCreate, int)) *CredentialCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CredentialCreateBulk{err: fmt.Errorf("calling to CredentialClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CredentialCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CredentialCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Credential.
func (c *CredentialClient) Update() *CredentialUpdate {
	mutation := newCredentialMutation(c.config, OpUpdate)
	return &CredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CredentialClient) UpdateOne(_m *Credential) *CredentialUpdateOne {
	mutation := newCredentialMutation(c.config, OpUpdateOne, withCredential(_m))
	return &CredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CredentialClient) UpdateOneID(id uuid.UUID) *CredentialUpdateOne {
	mutation := newCredentialMutation(c.config, OpUpdateOne, withCredentialID(id))
	return &CredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Credential.
func (c *CredentialClient) Delete() *CredentialDelete {
	mutation := newCredentialMutation(c.config, OpDelete)
	return &CredentialDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CredentialClient) DeleteOne(_m *Credential) *CredentialDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CredentialClient) DeleteOneID(id uuid.UUID) *CredentialDeleteOne {
	builder := c.Delete().Where(credential.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CredentialDeleteOne{builder}
}

// Query returns a query builder for Credential.
func (c *CredentialClient) Query() *CredentialQuery {
	return &CredentialQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCredential},
		inters: c.Interceptors(),
	}
}

// Get returns a Credential entity by its id.
func (c *CredentialClient) Get(ctx context.Context, id uuid.UUID) (*Credential, error) {
	return c.Query().Where(credential.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CredentialClient) GetX(ctx context.Context, id uuid.UUID) *Credential {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CredentialClient) Hooks() []Hook {
	return c.hooks.Credential
}

// Interceptors returns the client interceptors.
func (c *CredentialClient) Interceptors() []Interceptor {
	return c.inters.Credential
}

func (c *CredentialClient) mutate(ctx context.Context, m *CredentialMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CredentialCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CredentialUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CredentialUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CredentialDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown Credential mutation op: %q", m.Op())
	}
}

// FlowClient is a client for the Flow schema.
type FlowClient struct {
	config
}

// NewFlowClient returns a client for the Flow from the given config.
func NewFlowClient(c config) *FlowClient {
	return &FlowClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `flow.Hooks(f(g(h())))`.
func (c *FlowClient) Use(hooks ...Hook) {
	c.hooks.Flow = append(c.hooks.Flow, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `flow.Intercept(f(g(h())))`.
func (c *FlowClient) Intercept(interceptors ...Interceptor) {
	c.inters.Flow = append(c.inters.Flow, interceptors...)
}

// Create returns a builder for creating a Flow entity.
func (c *FlowClient) Create() *FlowCreate {
	mutation := newFlowMutation(c.config, OpCreate)
	return &FlowCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Flow entities.
func (c *FlowClient) CreateBulk(builders ...*FlowCreate) *FlowCreateBulk {
	return &FlowCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FlowClient) MapCreateBulk(slice any, setFunc func(*FlowCreate, int)) *FlowCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FlowCreateBulk{err: fmt.Errorf("calling to FlowClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FlowCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FlowCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Flow.
func (c *FlowClient) Update() *FlowUpdate {
	mutation := newFlowMutation(c.config, OpUpdate)
	return &FlowUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FlowClient) UpdateOne(_m *Flow) *FlowUpdateOne {
	mutation := newFlowMutation(c.config, OpUpdateOne, withFlow(_m))
	return &FlowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FlowClient) UpdateOneID(id uuid.UUID) *FlowUpdateOne {
	mutation := newFlowMutation(c.config, OpUpdateOne, withFlowID(id))
	return &FlowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Flow.
func (c *FlowClient) Delete() *FlowDelete {
	mutation := newFlowMutation(c.config, OpDelete)
	return &FlowDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FlowClient) DeleteOne(_m *Flow) *FlowDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FlowClient) DeleteOneID(id uuid.UUID) *FlowDeleteOne {
	builder := c.Delete().Where(flow.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FlowDeleteOne{builder}
}

// Query returns a query builder for Flow.
func (c *FlowClient) Query() *FlowQuery {
	return &FlowQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFlow},
		inters: c.Interceptors(),
	}
}

// Get returns a Flow entity by its id.
func (c *FlowClient) Get(ctx context.Context, id uuid.UUID) (*Flow, error) {
	return c.Query().Where(flow.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FlowClient) GetX(ctx context.Context, id uuid.UUID) *Flow {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FlowClient) Hooks() []Hook {
	return c.hooks.Flow
}

// Interceptors returns the client interceptors.
func (c *FlowClient) Interceptors() []Interceptor {
	return c.inters.Flow
}

func (c *FlowClient) mutate(ctx context.Context, m *FlowMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FlowCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FlowUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FlowUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FlowDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown Flow mutation op: %q", m.Op())
	}
}

// MemoryClient is a client for the Memory schema.
type MemoryClient struct {
	config
}

// NewMemoryClient returns a client for the Memory from the given config.
func NewMemoryClient(c config) *MemoryClient {
	return &MemoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memory.Hooks(f(g(h())))`.
func (c *MemoryClient) Use(hooks ...Hook) {
	c.hooks.Memory = append(c.hooks.Memory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memory.Intercept(f(g(h())))`.
func (c *MemoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.Memory = append(c.inters.Memory, interceptors...)
}

// Create returns a builder for creating a Memory entity.
func (c *MemoryClient) Create() *MemoryCreate {
	mutation := newMemoryMutation(c.config, OpCreate)
	return &MemoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Memory entities.
func (c *MemoryClient) CreateBulk(builders ...*MemoryCreate) *MemoryCreateBulk {
	return &MemoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryClient) MapCreateBulk(slice any, setFunc func(*MemoryCreate, int)) *MemoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryCreateBulk{err: fmt.Errorf("calling to MemoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Memory.
func (c *MemoryClient) Update() *MemoryUpdate {
	mutation := newMemoryMutation(c.config, OpUpdate)
	return &MemoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryClient) UpdateOne(_m *Memory) *MemoryUpdateOne {
	mutation := newMemoryMutation(c.config, OpUpdateOne, withMemory(_m))
	return &MemoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryClient) UpdateOneID(id uuid.UUID) *MemoryUpdateOne {
	mutation := newMemoryMutation(c.config, OpUpdateOne, withMemoryID(id))
	return &MemoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Memory.
func (c *MemoryClient) Delete() *MemoryDelete {
	mutation := newMemoryMutation(c.config, OpDelete)
	return &MemoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryClient) DeleteOne(_m *Memory) *MemoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryClient) DeleteOneID(id uuid.UUID) *MemoryDeleteOne {
	builder := c.Delete().Where(memory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryDeleteOne{builder}
}

// Query returns a query builder for Memory.
func (c *MemoryClient) Query() *MemoryQuery {
	return &MemoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemory},
		inters: c.Interceptors(),
	}
}

// Get returns a Memory entity by its id.
func (c *MemoryClient) Get(ctx context.Context, id uuid.UUID) (*Memory, error) {
	return c.Query().Where(memory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryClient) GetX(ctx context.Context, id uuid.UUID) *Memory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MemoryClient) Hooks() []Hook {
	return c.hooks.Memory
}

// Interceptors returns the client interceptors.
func (c *MemoryClient) Interceptors() []Interceptor {
	return c.inters.Memory
}

func (c *MemoryClient) mutate(ctx context.Context, m *MemoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown Memory mutation op: %q", m.Op())
	}
}

// PersonalSettingsClient is a client for the PersonalSettings schema.
type PersonalSettingsClient struct {
	config
}

// NewPersonalSettingsClient returns a client for the PersonalSettings from the given config.
func NewPersonalSettingsClient(c config) *PersonalSettingsClient {
	return &PersonalSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `personalsettings.Hooks(f(g(h())))`.
func (c *PersonalSettingsClient) Use(hooks ...Hook) {
	c.hooks.PersonalSettings = append(c.hooks.PersonalSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `personalsettings.Intercept(f(g(h())))`.
func (c *PersonalSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.PersonalSettings = append(c.inters.PersonalSettings, interceptors...)
}

// Create returns a builder for creating a PersonalSettings entity.
func (c *PersonalSettingsClient) Create() *PersonalSettingsCreate {
	mutation := newPersonalSettingsMutation(c.config, OpCreate)
	return &PersonalSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PersonalSettings entities.
func (c *PersonalSettingsClient) CreateBulk(builders ...*PersonalSettingsCreate) *PersonalSettingsCreateBulk {
	return &PersonalSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PersonalSettingsClient) MapCreateBulk(slice any, setFunc func(*PersonalSettingsCreate, int)) *PersonalSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PersonalSettingsCreateBulk{err: fmt.Errorf("calling to PersonalSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PersonalSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PersonalSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PersonalSettings.
func (c *PersonalSettingsClient) Update() *PersonalSettingsUpdate {
	mutation := newPersonalSettingsMutation(c.config, OpUpdate)
	return &PersonalSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PersonalSettingsClient) UpdateOne(_m *PersonalSettings) *PersonalSettingsUpdateOne {
	mutation := newPersonalSettingsMutation(c.config, OpUpdateOne, withPersonalSettings(_m))
	return &PersonalSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PersonalSettingsClient) UpdateOneID(id int) *PersonalSettingsUpdateOne {
	mutation := newPersonalSettingsMutation(c.config, OpUpdateOne, withPersonalSettingsID(id))
	return &PersonalSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PersonalSettings.
func (c *PersonalSettingsClient) Delete() *PersonalSettingsDelete {
	mutation := newPersonalSettingsMutation(c.config, OpDelete)
	return &PersonalSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PersonalSettingsClient) DeleteOne(_m *PersonalSettings) *PersonalSettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PersonalSettingsClient) DeleteOneID(id int) *PersonalSettingsDeleteOne {
	builder := c.Delete().Where(personalsettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PersonalSettingsDeleteOne{builder}
}

// Query returns a query builder for PersonalSettings.
func (c *PersonalSettingsClient) Query() *PersonalSettingsQuery {
	return &PersonalSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePersonalSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a PersonalSettings entity by its id.
func (c *PersonalSettingsClient) Get(ctx context.Context, id int) (*PersonalSettings, error) {
	return c.Query().Where(personalsettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PersonalSettingsClient) GetX(ctx context.Context, id int) *PersonalSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PersonalSettingsClient) Hooks() []Hook {
	return c.hooks.PersonalSettings
}

// Interceptors returns the client interceptors.
func (c *PersonalSettingsClient) Interceptors() []Interceptor {
	return c.inters.PersonalSettings
}

func (c *PersonalSettingsClient) mutate(ctx context.Context, m *PersonalSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PersonalSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PersonalSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PersonalSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PersonalSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown PersonalSettings mutation op: %q", m.Op())
	}
}

// ScheduledJobClient is a client for the ScheduledJob schema.
type ScheduledJobClient struct {
	config
}

// NewScheduledJobClient returns a client for the ScheduledJob from the given config.
func NewScheduledJobClient(c config) *ScheduledJobClient {
	return &ScheduledJobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `scheduledjob.Hooks(f(g(h())))`.
func (c *ScheduledJobClient) Use(hooks ...Hook) {
	c.hooks.ScheduledJob = append(c.hooks.ScheduledJob, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `scheduledjob.Intercept(f(g(h())))`.
func (c *ScheduledJobClient) Intercept(interceptors ...Interceptor) {
	c.inters.ScheduledJob = append(c.inters.ScheduledJob, interceptors...)
}

// Create returns a builder for creating a ScheduledJob entity.
func (c *ScheduledJobClient) Create() *ScheduledJobCreate {
	mutation := newScheduledJobMutation(c.config, OpCreate)
	return &ScheduledJobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ScheduledJob entities.
func (c *ScheduledJobClient) CreateBulk(builders ...*ScheduledJobCreate) *ScheduledJobCreateBulk {
	return &ScheduledJobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ScheduledJobClient) MapCreateBulk(slice any, setFunc func(*ScheduledJobCreate, int)) *ScheduledJobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ScheduledJobCreateBulk{err: fmt.Errorf("calling to ScheduledJobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ScheduledJobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ScheduledJobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ScheduledJob.
func (c *ScheduledJobClient) Update() *ScheduledJobUpdate {
	mutation := newScheduledJobMutation(c.config, OpUpdate)
	return &ScheduledJobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ScheduledJobClient) UpdateOne(_m *ScheduledJob) *ScheduledJobUpdateOne {
	mutation := newScheduledJobMutation(c.config, OpUpdateOne, withScheduledJob(_m))
	return &ScheduledJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ScheduledJobClient) UpdateOneID(id uuid.UUID) *ScheduledJobUpdateOne {
	mutation := newScheduledJobMutation(c.config, OpUpdateOne, withScheduledJobID(id))
	return &ScheduledJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ScheduledJob.
func (c *ScheduledJobClient) Delete() *ScheduledJobDelete {
	mutation := newScheduledJobMutation(c.config, OpDelete)
	return &ScheduledJobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ScheduledJobClient) DeleteOne(_m *ScheduledJob) *ScheduledJobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ScheduledJobClient) DeleteOneID(id uuid.UUID) *ScheduledJobDeleteOne {
	builder := c.Delete().Where(scheduledjob.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ScheduledJobDeleteOne{builder}
}

// Query returns a query builder for ScheduledJob.
func (c *ScheduledJobClient) Query() *ScheduledJobQuery {
	return &ScheduledJobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeScheduledJob},
		inters: c.Interceptors(),
	}
}

// Get returns a ScheduledJob entity by its id.
func (c *ScheduledJobClient) Get(ctx context.Context, id uuid.UUID) (*ScheduledJob, error) {
	return c.Query().Where(scheduledjob.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ScheduledJobClient) GetX(ctx context.Context, id uuid.UUID) *ScheduledJob {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ScheduledJobClient) Hooks() []Hook {
	return c.hooks.ScheduledJob
}

// Interceptors returns the client interceptors.
func (c *ScheduledJobClient) Interceptors() []Interceptor {
	return c.inters.ScheduledJob
}

func (c *ScheduledJobClient) mutate(ctx context.Context, m *ScheduledJobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ScheduledJobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ScheduledJobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ScheduledJobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ScheduledJobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown ScheduledJob mutation op: %q", m.Op())
	}
}

// SessionClient is a client for the Session schema.
type SessionClient struct {
	config
}

// NewSessionClient returns a client for the Session from the given config.
func NewSessionClient(c config) *SessionClient {
	return &SessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `session.Hooks(f(g(h())))`.
func (c *SessionClient) Use(hooks ...Hook) {
	c.hooks.Session = append(c.hooks.Session, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `session.Intercept(f(g(h())))`.
func (c *SessionClient) Intercept(interceptors ...Interceptor) {
	c.inters.Session = append(c.inters.Session, interceptors...)
}

// Create returns a builder for creating a Session entity.
func (c *SessionClient) Create() *SessionCreate {
	mutation := newSessionMutation(c.config, OpCreate)
	return &SessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Session entities.
func (c *SessionClient) CreateBulk(builders ...*SessionCreate) *SessionCreateBulk {
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionClient) MapCreateBulk(slice any, setFunc func(*SessionCreate, int)) *SessionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionCreateBulk{err: fmt.Errorf("calling to SessionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Session.
func (c *SessionClient) Update() *SessionUpdate {
	mutation := newSessionMutation(c.config, OpUpdate)
	return &SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionClient) UpdateOne(_m *Session) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSession(_m))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionClient) UpdateOneID(id string) *SessionUpdateOne {
	mutation := newSessionMutation(c.config, OpUpdateOne, withSessionID(id))
	return &SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Session.
func (c *SessionClient) Delete() *SessionDelete {
	mutation := newSessionMutation(c.config, OpDelete)
	return &SessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionClient) DeleteOne(_m *Session) *SessionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionClient) DeleteOneID(id string) *SessionDeleteOne {
	builder := c.Delete().Where(session.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionDeleteOne{builder}
}

// Query returns a query builder for Session.
func (c *SessionClient) Query() *SessionQuery {
	return &SessionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSession},
		inters: c.Interceptors(),
	}
}

// Get returns a Session entity by its id.
func (c *SessionClient) Get(ctx context.Context, id string) (*Session, error) {
	return c.Query().Where(session.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionClient) GetX(ctx context.Context, id string) *Session {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvents queries the events edge of a Session.
func (c *SessionClient) QueryEvents(_m *Session) *SessionEventQuery {
	query := (&SessionEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(session.Table, session.FieldID, id),
			sqlgraph.To(sessionevent.Table, sessionevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, session.EventsTable, session.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionClient) Hooks() []Hook {
	return c.hooks.Session
}

// Interceptors returns the client interceptors.
func (c *SessionClient) Interceptors() []Interceptor {
	return c.inters.Session
}

func (c *SessionClient) mutate(ctx context.Context, m *SessionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown Session mutation op: %q", m.Op())
	}
}

// SessionEventClient is a client for the SessionEvent schema.
type SessionEventClient struct {
	config
}

// NewSessionEventClient returns a client for the SessionEvent from the given config.
func NewSessionEventClient(c config) *SessionEventClient {
	return &SessionEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `sessionevent.Hooks(f(g(h())))`.
func (c *SessionEventClient) Use(hooks ...Hook) {
	c.hooks.SessionEvent = append(c.hooks.SessionEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `sessionevent.Intercept(f(g(h())))`.
func (c *SessionEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.SessionEvent = append(c.inters.SessionEvent, interceptors...)
}

// Create returns a builder for creating a SessionEvent entity.
func (c *SessionEventClient) Create() *SessionEventCreate {
	mutation := newSessionEventMutation(c.config, OpCreate)
	return &SessionEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SessionEvent entities.
func (c *SessionEventClient) CreateBulk(builders ...*SessionEventCreate) *SessionEventCreateBulk {
	return &SessionEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SessionEventClient) MapCreateBulk(slice any, setFunc func(*SessionEventCreate, int)) *SessionEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SessionEventCreateBulk{err: fmt.Errorf("calling to SessionEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SessionEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SessionEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SessionEvent.
func (c *SessionEventClient) Update() *SessionEventUpdate {
	mutation := newSessionEventMutation(c.config, OpUpdate)
	return &SessionEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SessionEventClient) UpdateOne(_m *SessionEvent) *SessionEventUpdateOne {
	mutation := newSessionEventMutation(c.config, OpUpdateOne, withSessionEvent(_m))
	return &SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SessionEventClient) UpdateOneID(id int) *SessionEventUpdateOne {
	mutation := newSessionEventMutation(c.config, OpUpdateOne, withSessionEventID(id))
	return &SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SessionEvent.
func (c *SessionEventClient) Delete() *SessionEventDelete {
	mutation := newSessionEventMutation(c.config, OpDelete)
	return &SessionEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SessionEventClient) DeleteOne(_m *SessionEvent) *SessionEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SessionEventClient) DeleteOneID(id int) *SessionEventDeleteOne {
	builder := c.Delete().Where(sessionevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SessionEventDeleteOne{builder}
}

// Query returns a query builder for SessionEvent.
func (c *SessionEventClient) Query() *SessionEventQuery {
	return &SessionEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSessionEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a SessionEvent entity by its id.
func (c *SessionEventClient) Get(ctx context.Context, id int) (*SessionEvent, error) {
	return c.Query().Where(sessionevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SessionEventClient) GetX(ctx context.Context, id int) *SessionEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySession queries the session edge of a SessionEvent.
func (c *SessionEventClient) QuerySession(_m *SessionEvent) *SessionQuery {
	query := (&SessionClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(sessionevent.Table, sessionevent.FieldID, id),
			sqlgraph.To(session.Table, session.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sessionevent.SessionTable, sessionevent.SessionColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SessionEventClient) Hooks() []Hook {
	return c.hooks.SessionEvent
}

// Interceptors returns the client interceptors.
func (c *SessionEventClient) Interceptors() []Interceptor {
	return c.inters.SessionEvent
}

func (c *SessionEventClient) mutate(ctx context.Context, m *SessionEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SessionEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SessionEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SessionEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SessionEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("personal: unknown SessionEvent mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		App, AppState, Credential, Flow, Memory, PersonalSettings, ScheduledJob,
		Session, SessionEvent []ent.Hook
	}
	inters struct {
		App, AppState, Credential, Flow, Memory, PersonalSettings, ScheduledJob,
		Session, SessionEvent []ent.Interceptor
	}
)
