// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/SAP/astonish/ent/platform"
)

// The DeviceSessionFunc type is an adapter to allow the use of ordinary
// function as DeviceSession mutator.
type DeviceSessionFunc func(context.Context, *platform.DeviceSessionMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f DeviceSessionFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.DeviceSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.DeviceSessionMutation", m)
}

// The EmailThreadIndexFunc type is an adapter to allow the use of ordinary
// function as EmailThreadIndex mutator.
type EmailThreadIndexFunc func(context.Context, *platform.EmailThreadIndexMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f EmailThreadIndexFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.EmailThreadIndexMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.EmailThreadIndexMutation", m)
}

// The LoginSessionFunc type is an adapter to allow the use of ordinary
// function as LoginSession mutator.
type LoginSessionFunc func(context.Context, *platform.LoginSessionMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f LoginSessionFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.LoginSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.LoginSessionMutation", m)
}

// The OIDCProviderFunc type is an adapter to allow the use of ordinary
// function as OIDCProvider mutator.
type OIDCProviderFunc func(context.Context, *platform.OIDCProviderMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f OIDCProviderFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.OIDCProviderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.OIDCProviderMutation", m)
}

// The OrgMembershipFunc type is an adapter to allow the use of ordinary
// function as OrgMembership mutator.
type OrgMembershipFunc func(context.Context, *platform.OrgMembershipMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f OrgMembershipFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.OrgMembershipMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.OrgMembershipMutation", m)
}

// The OrganizationFunc type is an adapter to allow the use of ordinary
// function as Organization mutator.
type OrganizationFunc func(context.Context, *platform.OrganizationMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f OrganizationFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.OrganizationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.OrganizationMutation", m)
}

// The PendingLinkCodeFunc type is an adapter to allow the use of ordinary
// function as PendingLinkCode mutator.
type PendingLinkCodeFunc func(context.Context, *platform.PendingLinkCodeMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PendingLinkCodeFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PendingLinkCodeMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PendingLinkCodeMutation", m)
}

// The PlatformMCPServerFunc type is an adapter to allow the use of ordinary
// function as PlatformMCPServer mutator.
type PlatformMCPServerFunc func(context.Context, *platform.PlatformMCPServerMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformMCPServerFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformMCPServerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformMCPServerMutation", m)
}

// The PlatformNetworkPolicyFunc type is an adapter to allow the use of ordinary
// function as PlatformNetworkPolicy mutator.
type PlatformNetworkPolicyFunc func(context.Context, *platform.PlatformNetworkPolicyMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformNetworkPolicyFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformNetworkPolicyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformNetworkPolicyMutation", m)
}

// The PlatformSecretFunc type is an adapter to allow the use of ordinary
// function as PlatformSecret mutator.
type PlatformSecretFunc func(context.Context, *platform.PlatformSecretMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformSecretFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformSecretMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformSecretMutation", m)
}

// The PlatformSettingFunc type is an adapter to allow the use of ordinary
// function as PlatformSetting mutator.
type PlatformSettingFunc func(context.Context, *platform.PlatformSettingMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformSettingFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformSettingMutation", m)
}

// The PlatformSkillFunc type is an adapter to allow the use of ordinary
// function as PlatformSkill mutator.
type PlatformSkillFunc func(context.Context, *platform.PlatformSkillMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformSkillFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformSkillMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformSkillMutation", m)
}

// The PlatformSkillFileFunc type is an adapter to allow the use of ordinary
// function as PlatformSkillFile mutator.
type PlatformSkillFileFunc func(context.Context, *platform.PlatformSkillFileMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f PlatformSkillFileFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.PlatformSkillFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.PlatformSkillFileMutation", m)
}

// The SandboxLayerFunc type is an adapter to allow the use of ordinary
// function as SandboxLayer mutator.
type SandboxLayerFunc func(context.Context, *platform.SandboxLayerMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f SandboxLayerFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.SandboxLayerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.SandboxLayerMutation", m)
}

// The SandboxTemplateFunc type is an adapter to allow the use of ordinary
// function as SandboxTemplate mutator.
type SandboxTemplateFunc func(context.Context, *platform.SandboxTemplateMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f SandboxTemplateFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.SandboxTemplateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.SandboxTemplateMutation", m)
}

// The ToolIndexFunc type is an adapter to allow the use of ordinary
// function as ToolIndex mutator.
type ToolIndexFunc func(context.Context, *platform.ToolIndexMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f ToolIndexFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.ToolIndexMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.ToolIndexMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *platform.UserMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.UserMutation", m)
}

// The UserChannelFunc type is an adapter to allow the use of ordinary
// function as UserChannel mutator.
type UserChannelFunc func(context.Context, *platform.UserChannelMutation) (platform.Value, error)

// Mutate calls f(ctx, m).
func (f UserChannelFunc) Mutate(ctx context.Context, m platform.Mutation) (platform.Value, error) {
	if mv, ok := m.(*platform.UserChannelMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *platform.UserChannelMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, platform.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m platform.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m platform.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m platform.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op platform.Op) Condition {
	return func(_ context.Context, m platform.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m platform.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m platform.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m platform.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk platform.Hook, cond Condition) platform.Hook {
	return func(next platform.Mutator) platform.Mutator {
		return platform.MutateFunc(func(ctx context.Context, m platform.Mutation) (platform.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, platform.Delete|platform.Create)
func On(hk platform.Hook, op platform.Op) platform.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, platform.Update|platform.UpdateOne)
func Unless(hk platform.Hook, op platform.Op) platform.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) platform.Hook {
	return func(platform.Mutator) platform.Mutator {
		return platform.MutateFunc(func(context.Context, platform.Mutation) (platform.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []platform.Hook {
//		return []platform.Hook{
//			Reject(platform.Delete|platform.Update),
//		}
//	}
func Reject(op platform.Op) platform.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []platform.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...platform.Hook) Chain {
	return Chain{append([]platform.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() platform.Hook {
	return func(mutator platform.Mutator) platform.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...platform.Hook) Chain {
	newHooks := make([]platform.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
