package store

import (
	"context"
	"time"
)

// --------------------------------------------------------------------------
// Sandbox template store (platform-scoped, DAG)
// --------------------------------------------------------------------------
//
// The template hierarchy is a directed acyclic graph rooted at the deployment-
// wide "@base" template (scope=global, parent=NULL). Templates inherit from a
// parent via the overlay layer chain — a template row's TopLayerID is the
// most-recently-added layer; the full chain is walked by following
// parent_template_id links and collecting top_layer_id at each step.
//
// Four scopes exist (docs/architecture/sandbox-backends.md §3.8):
//
//   - global:   deployment-wide; only "@base". Superadmin-only mutations.
//   - org:      visible to every team/user in the owning organization.
//   - team:     visible to a single team. Fleet templates are team-scoped
//               with Purpose="fleet".
//   - personal: visible only to the owning user.
//
// In personal mode, the filestore implementation retains its JSON template
// registry (TemplateMeta in pkg/sandbox). The DAG fields (ParentTemplateID,
// Scope, TopLayerID) are marshalled but ignored — personal-mode templates
// remain flat. See §Personal-mode invariants in the architecture doc.

// SandboxTemplateScope enumerates the four scope values.
type SandboxTemplateScope string

const (
	SandboxTemplateScopeGlobal   SandboxTemplateScope = "global"
	SandboxTemplateScopeOrg      SandboxTemplateScope = "org"
	SandboxTemplateScopeTeam     SandboxTemplateScope = "team"
	SandboxTemplateScopePersonal SandboxTemplateScope = "personal"
)

// SandboxTemplatePurpose is an optional discriminator within a scope. The only
// defined value today is "fleet" (team-scoped templates generated by the fleet
// pipeline). Empty string means a normal human-authored template.
type SandboxTemplatePurpose string

const (
	SandboxTemplatePurposeFleet SandboxTemplatePurpose = "fleet"
)

// SandboxTemplate is a DAG node.
//
// Invariants:
//   - Slug is unique within (Scope, OwnerID). Owner is orgID for scope=org,
//     teamID for scope=team, userID for scope=personal, empty for scope=global.
//   - ParentTemplateID==nil iff Slug="base" and Scope=global (the root).
//   - TopLayerID==nil means the template is layer-less (an alias of its
//     parent); Resolve walks to the nearest ancestor with a non-nil TopLayerID.
type SandboxTemplate struct {
	ID              string                 `json:"id"`
	Slug            string                 `json:"slug"`
	Scope           SandboxTemplateScope   `json:"scope"`
	OwnerID         string                 `json:"owner_id,omitempty"`
	Purpose         SandboxTemplatePurpose `json:"purpose,omitempty"`
	Name            string                 `json:"name"`
	Description     string                 `json:"description,omitempty"`
	ParentTemplateID *string               `json:"parent_template_id,omitempty"`
	TopLayerID      *string                `json:"top_layer_id,omitempty"`
	Version         int                    `json:"version"`
	CreatedBy       string                 `json:"created_by,omitempty"`
	CreatedAt       time.Time              `json:"created_at"`
	UpdatedAt       time.Time              `json:"updated_at"`
}

// SandboxTemplateFilter narrows list queries. Zero-value fields are ignored.
type SandboxTemplateFilter struct {
	Scope   SandboxTemplateScope
	OwnerID string
	Purpose SandboxTemplatePurpose
}

// ResolvedTemplateChain is the ordered list of layer IDs composing a
// template's overlay (oldest parent first, top-most last). The last element is
// the template's own TopLayerID (if any). This is the order consumed by
// overlayfs as `lowerdir` entries — overlayfs requires the top-most entry
// first in the comma-separated list, so callers typically reverse for mounting.
type ResolvedTemplateChain struct {
	TemplateID string
	LayerIDs   []string // oldest first
}

// SandboxTemplateStore manages the sandbox template DAG. Lives at platform
// scope (templates cross org boundaries via the global "@base"); see §7 of
// the architecture doc for schema placement rationale.
type SandboxTemplateStore interface {
	// Create inserts a new template row. Slug+Scope+OwnerID must be unique.
	// The implementation MUST reject cycles in the parent chain.
	Create(ctx context.Context, tpl *SandboxTemplate) error

	// GetByID returns a single template by primary key. Returns nil, nil if
	// not found.
	GetByID(ctx context.Context, id string) (*SandboxTemplate, error)

	// GetBySlug returns the template matching (scope, ownerID, slug).
	// ownerID is ignored for scope=global. Returns nil, nil if not found.
	GetBySlug(ctx context.Context, scope SandboxTemplateScope, ownerID, slug string) (*SandboxTemplate, error)

	// List returns templates matching the filter, ordered by (scope, slug).
	List(ctx context.Context, filter SandboxTemplateFilter) ([]*SandboxTemplate, error)

	// Update mutates mutable fields (Name, Description, Purpose, TopLayerID,
	// Version, UpdatedAt). Scope, OwnerID, and ParentTemplateID are immutable
	// after creation; implementations MUST reject changes to them.
	Update(ctx context.Context, tpl *SandboxTemplate) error

	// Delete removes the template row. Callers are responsible for
	// decrementing the ref_count on TopLayerID; the GC reconciler will reap
	// the layer bytes asynchronously.
	Delete(ctx context.Context, id string) error

	// Resolve walks the parent chain and returns the ordered list of layer
	// IDs (oldest first). Returns ErrUnsupported on stores that do not model
	// the DAG (filestore).
	Resolve(ctx context.Context, id string) (*ResolvedTemplateChain, error)

	// ListRoots returns templates with no parent (only the global "@base"
	// qualifies today). Useful for admin tools.
	ListRoots(ctx context.Context) ([]*SandboxTemplate, error)
}

// --------------------------------------------------------------------------
// Layer store (content-addressed, platform-scoped)
// --------------------------------------------------------------------------
//
// Layers are tar+zstd streams of a filesystem delta, identified by the SHA-256
// of their canonical uncompressed tar. Each layer is stored once on CephFS at
// /mnt/astonish-layers/<sha256>/rootfs/ and referenced by any number of
// templates and evicted session uppers.
//
// RefCount discipline:
//   - Incremented atomically when a template or session starts referencing
//     the layer (template create/update with new top_layer, session evict
//     producing a new upper layer, template refresh).
//   - Decremented atomically when a referrer is deleted or replaced.
//   - RefCount==0 and AddedAt older than the grace period (§5.12) means the
//     GC reconciler MAY reclaim the layer directory from CephFS.
//
// Personal mode does not implement this interface; the filestore returns
// ErrUnsupported for all methods.

// SandboxLayer is a content-addressed rootfs delta.
type SandboxLayer struct {
	LayerID      string    `json:"layer_id"` // sha256 hex of canonical tar
	ParentLayer  *string   `json:"parent_layer,omitempty"`
	CephFSPath   string    `json:"cephfs_path"` // /mnt/astonish-layers/<layer_id>
	SizeBytes    int64     `json:"size_bytes"`
	RefCount     int       `json:"ref_count"`
	CreatedBy    string    `json:"created_by,omitempty"`
	AddedAt      time.Time `json:"added_at"`
	LastReferenced time.Time `json:"last_referenced"`
}

// LayerStore manages the content-addressed layer registry. Implementations
// MUST treat all writes as transactional: PutLayer + ref-count adjustments
// that happen together must be atomic.
type LayerStore interface {
	// PutLayer inserts a new layer row. MUST be idempotent: if a row with the
	// same LayerID already exists (content dedup), the call succeeds without
	// modifying the existing row's RefCount. Callers are responsible for
	// calling IncrementRefCount separately to record a new reference.
	PutLayer(ctx context.Context, layer *SandboxLayer) error

	// GetLayer returns a layer by content-address. Returns nil, nil if absent.
	GetLayer(ctx context.Context, layerID string) (*SandboxLayer, error)

	// IncrementRefCount atomically increases RefCount by 1. Returns
	// ErrNotFound if the layer is absent. Implementations SHOULD also update
	// LastReferenced to now().
	IncrementRefCount(ctx context.Context, layerID string) error

	// DecrementRefCount atomically decreases RefCount by 1. RefCount MUST NOT
	// go negative; implementations return an error in that case.
	DecrementRefCount(ctx context.Context, layerID string) error

	// ListUnreferenced returns all layers with RefCount==0 that were added
	// before (now - grace). This is the candidate set for GC.
	ListUnreferenced(ctx context.Context, grace time.Duration) ([]*SandboxLayer, error)

	// ListAll returns every layer row regardless of ref_count. Used by the
	// sandbox-audit command to diff PG state against on-disk directories.
	ListAll(ctx context.Context) ([]*SandboxLayer, error)

	// DeleteLayer removes the registry row. Callers remove the CephFS bytes
	// separately. Returns an error if RefCount>0.
	DeleteLayer(ctx context.Context, layerID string) error
}

// --------------------------------------------------------------------------
// Chat event journal (team-scoped, cross-pod continuity)
// --------------------------------------------------------------------------
//
// The journal backs the cross-pod chat continuity design (§5.14). One producer
// holds a PG advisory lock per chat session; consumers (SSE streams) replay
// from (chat_session_id, seq) and tail new events via LISTEN/NOTIFY. Events
// are retained until chat close (ON DELETE CASCADE from chat_sessions).
//
// This interface is intentionally narrow; the fan-out + advisory-lock logic
// lives in pkg/sandbox (or its successor pkg/chat) and uses this interface as
// the persistence layer only.

// ChatEvent is one journal row.
type ChatEvent struct {
	ChatSessionID string    `json:"chat_session_id"`
	Seq           int64     `json:"seq"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"` // JSON-encoded
	ProducerPod   string    `json:"producer_pod,omitempty"`
	CreatedAt     time.Time `json:"created_at"`
}

// ChatEventJournal is the team-scoped append-only event journal.
type ChatEventJournal interface {
	// Append writes one or more events for a chat session. The implementation
	// MUST assign monotonic Seq values (starting at 1) per chat_session_id
	// and return the assigned values in order. Events within a single call
	// are written in one transaction.
	//
	// Callers are expected to hold the per-chat advisory lock (see §5.14) so
	// that only one producer writes for a given chat_session_id at a time.
	Append(ctx context.Context, events []*ChatEvent) error

	// ReadSince returns events with Seq > afterSeq for the given chat
	// session, in Seq order, up to limit rows. limit<=0 means "no limit".
	ReadSince(ctx context.Context, chatSessionID string, afterSeq int64, limit int) ([]*ChatEvent, error)

	// LastSeq returns the highest Seq for the chat session, or 0 if no
	// events are recorded.
	LastSeq(ctx context.Context, chatSessionID string) (int64, error)
}

// --------------------------------------------------------------------------
// Sandbox session store (team-scoped runtime metadata)
// --------------------------------------------------------------------------
//
// SandboxSession is the platform-scoped runtime record for one live (or
// evicted) sandbox. It tracks the bindings a backend cares about:
//
//   - SessionID:      stable caller-supplied identifier (chat session or
//                     fleet task key). Primary key.
//   - ContainerName:  Incus container name (or K8s pod name once Phase C
//                     ships). One-to-one with SessionID.
//   - TemplateID:     platform.sandbox_templates.id the session was cloned
//                     from. TEXT-encoded UUID in platform mode; bare slug
//                     in personal mode (where the DAG is flat).
//   - UpperLayerID:   platform.sandbox_layers.layer_id of the evicted upper
//                     when State=Evicted. Empty while the session is live.
//   - State:          creating/running/evicting/evicted/resuming/terminated
//                     — mirrors the {team_schema}.sandbox_sessions CHECK.
//                     Personal-mode filestore only uses running/evicted.
//   - ExposedPorts:   list of ports proxied into the container. Serialized
//                     as JSONB in platform mode, []int in filestore.
//   - BaseDomain:     subdomain root used by the proxy tier to construct
//                     per-port hostnames. Optional.
//   - Pinned:         manual "do not reap" flag set by `sandbox create`.
//   - CreatedBy:      user ID that opened the session (FK-shaped but not
//                     enforced across DBs). Optional in personal mode.
//   - CreatedAt / UpdatedAt / LastActiveAt: standard audit timestamps.
//
// The store is a thin persistence layer; registry-level semantics
// (resolve-by-prefix, reap-against-live-containers) remain in
// pkg/sandbox.SessionRegistry as higher-level operations over this store.

// SandboxSessionState enumerates the lifecycle phases tracked in the
// {team_schema}.sandbox_sessions.state column.
type SandboxSessionState string

const (
	SandboxSessionStateCreating   SandboxSessionState = "creating"
	SandboxSessionStateRunning    SandboxSessionState = "running"
	SandboxSessionStateEvicting   SandboxSessionState = "evicting"
	SandboxSessionStateEvicted    SandboxSessionState = "evicted"
	SandboxSessionStateResuming   SandboxSessionState = "resuming"
	SandboxSessionStateTerminated SandboxSessionState = "terminated"
)

// SandboxSession is one session metadata row.
//
// The SessionID maps to the {team_schema}.sandbox_sessions.id column.
// ChatSessionID is a separate (FK-shaped, not enforced) reference to the
// chat session in {team_schema}.sessions. In personal mode and in the
// common one-chat-one-sandbox case, callers MAY set SessionID == ChatSessionID.
type SandboxSession struct {
	SessionID      string              `json:"session_id"`
	ChatSessionID  string              `json:"chat_session_id"`
	Backend        string              `json:"backend"` // "incus" | "k8s"
	ContainerName  string              `json:"container_name,omitempty"`
	TemplateID     string              `json:"template_id"`
	UpperLayerID   string              `json:"upper_layer_id,omitempty"`
	State          SandboxSessionState `json:"state"`
	PodName        string              `json:"pod_name,omitempty"`
	NodeName       string              `json:"node_name,omitempty"`
	ExposedPorts   []int               `json:"exposed_ports,omitempty"`
	BaseDomain     string              `json:"base_domain,omitempty"`
	Pinned         bool                `json:"pinned,omitempty"`
	CreatedBy      string              `json:"created_by,omitempty"`
	CreatedAt      time.Time           `json:"created_at"`
	UpdatedAt      time.Time           `json:"updated_at"`
	LastActiveAt   time.Time           `json:"last_active_at"`
}

// SandboxSessionFilter narrows list queries. Zero-value fields are ignored.
type SandboxSessionFilter struct {
	State         SandboxSessionState // exact match
	CreatedBy     string              // exact user id
	Pinned        *bool               // nil = ignore; true/false = exact
	ContainerName string              // exact match (useful for reverse lookup)
}

// SandboxSessionStore manages team-scoped sandbox runtime metadata. In
// platform mode it backs {team_schema}.sandbox_sessions; in personal mode
// it backs ~/.local/share/astonish/sandbox/sandbox_sessions.json.
//
// Implementations MUST be safe for concurrent use.
type SandboxSessionStore interface {
	// Put inserts or replaces the row keyed by SessionID. CreatedAt is
	// preserved across replaces (the implementation keeps the earliest
	// CreatedAt it has seen); UpdatedAt is bumped to now().
	Put(ctx context.Context, sess *SandboxSession) error

	// Get returns the row by SessionID, or nil, nil if absent.
	Get(ctx context.Context, sessionID string) (*SandboxSession, error)

	// GetByContainerName returns the row whose ContainerName matches
	// exactly. Returns nil, nil if no row matches. Useful for the
	// backend-side reverse lookup during port-expose flows.
	GetByContainerName(ctx context.Context, containerName string) (*SandboxSession, error)

	// List returns rows matching the filter, ordered by CreatedAt DESC.
	List(ctx context.Context, filter SandboxSessionFilter) ([]*SandboxSession, error)

	// Delete removes the row by SessionID. Returns nil (no error) if the
	// row does not exist — Delete is idempotent to match the pkg/sandbox
	// SessionRegistry.Remove contract that preceded this interface.
	Delete(ctx context.Context, sessionID string) error

	// UpdateState transitions the lifecycle state and bumps UpdatedAt /
	// LastActiveAt. Returns an error if the row is absent. Platform-mode
	// implementations MAY enforce valid transitions; personal-mode MAY
	// accept any transition.
	UpdateState(ctx context.Context, sessionID string, state SandboxSessionState) error

	// UpdatePorts replaces the ExposedPorts list. Returns an error if the
	// row is absent.
	UpdatePorts(ctx context.Context, sessionID string, ports []int) error

	// SetBaseDomain sets BaseDomain on an existing row. Returns an error
	// if the row is absent.
	SetBaseDomain(ctx context.Context, sessionID, baseDomain string) error

	// SetPinned toggles the Pinned flag on an existing row.
	SetPinned(ctx context.Context, sessionID string, pinned bool) error

	// SetUpperLayer associates an evicted-upper layer with the session.
	// Passing empty string clears the association. Callers are responsible
	// for the corresponding LayerStore ref_count adjustment in the same
	// transaction when applicable (pgstore provides that guarantee).
	SetUpperLayer(ctx context.Context, sessionID, upperLayerID string) error
}
