// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// App is the predicate function for app builders.
type App func(*sql.Selector)

// AppState is the predicate function for appstate builders.
type AppState func(*sql.Selector)

// Credential is the predicate function for credential builders.
type Credential func(*sql.Selector)

// Flow is the predicate function for flow builders.
type Flow func(*sql.Selector)

// Memory is the predicate function for memory builders.
type Memory func(*sql.Selector)

// PersonalSettings is the predicate function for personalsettings builders.
type PersonalSettings func(*sql.Selector)

// ScheduledJob is the predicate function for scheduledjob builders.
type ScheduledJob func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SessionEvent is the predicate function for sessionevent builders.
type SessionEvent func(*sql.Selector)
