// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DeviceSession is the predicate function for devicesession builders.
type DeviceSession func(*sql.Selector)

// EmailThreadIndex is the predicate function for emailthreadindex builders.
type EmailThreadIndex func(*sql.Selector)

// LoginSession is the predicate function for loginsession builders.
type LoginSession func(*sql.Selector)

// OIDCProvider is the predicate function for oidcprovider builders.
type OIDCProvider func(*sql.Selector)

// OrgMembership is the predicate function for orgmembership builders.
type OrgMembership func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// PendingLinkCode is the predicate function for pendinglinkcode builders.
type PendingLinkCode func(*sql.Selector)

// PlatformMCPServer is the predicate function for platformmcpserver builders.
type PlatformMCPServer func(*sql.Selector)

// PlatformNetworkPolicy is the predicate function for platformnetworkpolicy builders.
type PlatformNetworkPolicy func(*sql.Selector)

// PlatformSecret is the predicate function for platformsecret builders.
type PlatformSecret func(*sql.Selector)

// PlatformSetting is the predicate function for platformsetting builders.
type PlatformSetting func(*sql.Selector)

// PlatformSkill is the predicate function for platformskill builders.
type PlatformSkill func(*sql.Selector)

// PlatformSkillFile is the predicate function for platformskillfile builders.
type PlatformSkillFile func(*sql.Selector)

// SandboxLayer is the predicate function for sandboxlayer builders.
type SandboxLayer func(*sql.Selector)

// SandboxTemplate is the predicate function for sandboxtemplate builders.
type SandboxTemplate func(*sql.Selector)

// ToolIndex is the predicate function for toolindex builders.
type ToolIndex func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserChannel is the predicate function for userchannel builders.
type UserChannel func(*sql.Selector)
