name: Publish to PyPI

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Run workflow on version tags, e.g. 1.0.0

jobs:
  deploy:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    # Only publish to PyPI when pushing to the main repository
    if: github.repository == 'schardosin/astonish'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          # Install dependencies directly from PyPI
          pip install appdirs==1.4.4 generative-ai-hub-sdk[all]==4.10.2 langchain-ollama==0.3.1 langchain==0.3.24 langgraph==0.3.27 langgraph-checkpoint-sqlite==2.0.6 pydantic==2.10.6 colorama==0.4.6 aiosqlite==0.21.0 grandalf==0.8 pykwalify==1.8.0 inquirer==3.4.0 langchain-anthropic==0.3.12
          # Try multiple approaches to install langchain-mcp-adapters
          pip install langchain-mcp-adapters==0.0.9 || \
          pip install --index-url https://pypi.org/simple/ langchain-mcp-adapters==0.0.9 || \
          pip install --no-deps langchain-mcp-adapters==0.0.9 || \
          pip install --pre langchain-mcp-adapters==0.0.9 || \
          echo "Warning: Could not install langchain-mcp-adapters==0.0.9, continuing anyway"

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
